// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loan.proto

package com_lending_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Loan struct {
	Status                    string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CalledDue                 bool     `protobuf:"varint,2,opt,name=calledDue,proto3" json:"calledDue,omitempty"`
	DateClosed                string   `protobuf:"bytes,3,opt,name=dateClosed,proto3" json:"dateClosed,omitempty"`
	DateOpened                string   `protobuf:"bytes,4,opt,name=dateOpened,proto3" json:"dateOpened,omitempty"`
	LoanNumber                string   `protobuf:"bytes,5,opt,name=loanNumber,proto3" json:"loanNumber,omitempty"`
	DaysPastDue               int64    `protobuf:"varint,6,opt,name=daysPastDue,proto3" json:"daysPastDue,omitempty"`
	CurrentOwner              string   `protobuf:"bytes,7,opt,name=currentOwner,proto3" json:"currentOwner,omitempty"`
	TransferFrom              string   `protobuf:"bytes,8,opt,name=transferFrom,proto3" json:"transferFrom,omitempty"`
	SourceAccountNumber       string   `protobuf:"bytes,9,opt,name=sourceAccountNumber,proto3" json:"sourceAccountNumber,omitempty"`
	AmountPastDueInCents      int64    `protobuf:"varint,10,opt,name=amountPastDueInCents,proto3" json:"amountPastDueInCents,omitempty"`
	CurrentBalanceInCents     int64    `protobuf:"varint,11,opt,name=currentBalanceInCents,proto3" json:"currentBalanceInCents,omitempty"`
	LastPaymentContingent     bool     `protobuf:"varint,12,opt,name=lastPaymentContingent,proto3" json:"lastPaymentContingent,omitempty"`
	TransferEffectiveDate     string   `protobuf:"bytes,13,opt,name=transferEffectiveDate,proto3" json:"transferEffectiveDate,omitempty"`
	CalledDueAmountInCents    int64    `protobuf:"varint,14,opt,name=calledDueAmountInCents,proto3" json:"calledDueAmountInCents,omitempty"`
	OutstandingBalanceInCents int64    `protobuf:"varint,15,opt,name=outstandingBalanceInCents,proto3" json:"outstandingBalanceInCents,omitempty"`
	InCollectionBeforeClosed  bool     `protobuf:"varint,17,opt,name=inCollectionBeforeClosed,proto3" json:"inCollectionBeforeClosed,omitempty"`
	OriginalLoanAmountInCents int64    `protobuf:"varint,18,opt,name=originalLoanAmountInCents,proto3" json:"originalLoanAmountInCents,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Loan) Reset()         { *m = Loan{} }
func (m *Loan) String() string { return proto.CompactTextString(m) }
func (*Loan) ProtoMessage()    {}
func (*Loan) Descriptor() ([]byte, []int) {
	return fileDescriptor_de6e711e9786e730, []int{0}
}

func (m *Loan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loan.Unmarshal(m, b)
}
func (m *Loan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loan.Marshal(b, m, deterministic)
}
func (m *Loan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loan.Merge(m, src)
}
func (m *Loan) XXX_Size() int {
	return xxx_messageInfo_Loan.Size(m)
}
func (m *Loan) XXX_DiscardUnknown() {
	xxx_messageInfo_Loan.DiscardUnknown(m)
}

var xxx_messageInfo_Loan proto.InternalMessageInfo

func (m *Loan) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Loan) GetCalledDue() bool {
	if m != nil {
		return m.CalledDue
	}
	return false
}

func (m *Loan) GetDateClosed() string {
	if m != nil {
		return m.DateClosed
	}
	return ""
}

func (m *Loan) GetDateOpened() string {
	if m != nil {
		return m.DateOpened
	}
	return ""
}

func (m *Loan) GetLoanNumber() string {
	if m != nil {
		return m.LoanNumber
	}
	return ""
}

func (m *Loan) GetDaysPastDue() int64 {
	if m != nil {
		return m.DaysPastDue
	}
	return 0
}

func (m *Loan) GetCurrentOwner() string {
	if m != nil {
		return m.CurrentOwner
	}
	return ""
}

func (m *Loan) GetTransferFrom() string {
	if m != nil {
		return m.TransferFrom
	}
	return ""
}

func (m *Loan) GetSourceAccountNumber() string {
	if m != nil {
		return m.SourceAccountNumber
	}
	return ""
}

func (m *Loan) GetAmountPastDueInCents() int64 {
	if m != nil {
		return m.AmountPastDueInCents
	}
	return 0
}

func (m *Loan) GetCurrentBalanceInCents() int64 {
	if m != nil {
		return m.CurrentBalanceInCents
	}
	return 0
}

func (m *Loan) GetLastPaymentContingent() bool {
	if m != nil {
		return m.LastPaymentContingent
	}
	return false
}

func (m *Loan) GetTransferEffectiveDate() string {
	if m != nil {
		return m.TransferEffectiveDate
	}
	return ""
}

func (m *Loan) GetCalledDueAmountInCents() int64 {
	if m != nil {
		return m.CalledDueAmountInCents
	}
	return 0
}

func (m *Loan) GetOutstandingBalanceInCents() int64 {
	if m != nil {
		return m.OutstandingBalanceInCents
	}
	return 0
}

func (m *Loan) GetInCollectionBeforeClosed() bool {
	if m != nil {
		return m.InCollectionBeforeClosed
	}
	return false
}

func (m *Loan) GetOriginalLoanAmountInCents() int64 {
	if m != nil {
		return m.OriginalLoanAmountInCents
	}
	return 0
}

func init() {
	proto.RegisterType((*Loan)(nil), "com.lending.proto.Loan")
}

func init() { proto.RegisterFile("loan.proto", fileDescriptor_de6e711e9786e730) }

var fileDescriptor_de6e711e9786e730 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xd1, 0x6b, 0xd4, 0x40,
	0x10, 0xc6, 0x89, 0x6d, 0xaf, 0xbd, 0xb9, 0xaa, 0x74, 0xd5, 0xb2, 0x82, 0xc8, 0xd1, 0xa7, 0x7b,
	0x2a, 0xa2, 0xe2, 0x83, 0xf8, 0xd2, 0xa4, 0x0a, 0x42, 0xb1, 0xc7, 0xfd, 0x07, 0xd3, 0xcd, 0xe4,
	0x08, 0x6c, 0x66, 0xcb, 0xee, 0x44, 0xe9, 0x3f, 0x2f, 0xb2, 0x9b, 0xa4, 0x77, 0x95, 0xe4, 0x71,
	0xbf, 0xdf, 0x7c, 0x3b, 0xdf, 0xb0, 0xb3, 0x00, 0xd6, 0x21, 0x5f, 0xde, 0x7b, 0x27, 0x4e, 0x9d,
	0x19, 0xd7, 0x5c, 0x5a, 0xe2, 0xb2, 0xe6, 0x6d, 0x27, 0x5d, 0xfc, 0x3d, 0x82, 0xc3, 0x1b, 0x87,
	0xac, 0xce, 0x61, 0x16, 0x04, 0xa5, 0x0d, 0x3a, 0x5b, 0x66, 0xab, 0xf9, 0xa6, 0x3f, 0xa9, 0x77,
	0x30, 0x37, 0x68, 0x2d, 0x95, 0xd7, 0x2d, 0xe9, 0x67, 0xcb, 0x6c, 0x75, 0xb2, 0xd9, 0x09, 0xea,
	0x3d, 0x40, 0x89, 0x42, 0x85, 0x75, 0x81, 0x4a, 0x7d, 0x90, 0x9c, 0x7b, 0xca, 0xc0, 0x6f, 0xef,
	0x89, 0xa9, 0xd4, 0x87, 0x3b, 0xde, 0x29, 0x91, 0xc7, 0x7c, 0xbf, 0xda, 0xe6, 0x8e, 0xbc, 0x3e,
	0xea, 0xf8, 0x4e, 0x51, 0x4b, 0x58, 0x94, 0xf8, 0x10, 0xd6, 0x18, 0x24, 0xf6, 0x9f, 0x2d, 0xb3,
	0xd5, 0xc1, 0x66, 0x5f, 0x52, 0x17, 0x70, 0x6a, 0x5a, 0xef, 0x89, 0xe5, 0xf6, 0x0f, 0x93, 0xd7,
	0xc7, 0xe9, 0x8e, 0x27, 0x5a, 0xac, 0x11, 0x8f, 0x1c, 0x2a, 0xf2, 0x3f, 0xbc, 0x6b, 0xf4, 0x49,
	0x57, 0xb3, 0xaf, 0xa9, 0x0f, 0xf0, 0x2a, 0xb8, 0xd6, 0x1b, 0xba, 0x32, 0xc6, 0xb5, 0x2c, 0x7d,
	0xa4, 0x79, 0x2a, 0x1d, 0x43, 0xea, 0x23, 0xbc, 0xc6, 0x26, 0x9e, 0xfb, 0x28, 0x3f, 0xb9, 0x20,
	0x96, 0xa0, 0x21, 0x85, 0x1c, 0x65, 0xea, 0x33, 0xbc, 0xe9, 0x93, 0xe5, 0x68, 0x91, 0xcd, 0xa3,
	0x69, 0x91, 0x4c, 0xe3, 0x30, 0xba, 0x2c, 0x06, 0x59, 0xe3, 0x43, 0x43, 0x2c, 0x85, 0x63, 0xa9,
	0x79, 0x4b, 0x2c, 0xfa, 0x34, 0xbd, 0xc7, 0x38, 0x8c, 0xae, 0x61, 0xc2, 0xef, 0x55, 0x45, 0x46,
	0xea, 0xdf, 0x74, 0x8d, 0x42, 0xfa, 0x79, 0x9a, 0x69, 0x1c, 0xaa, 0x2f, 0x70, 0xfe, 0xf8, 0xbc,
	0x57, 0x69, 0x84, 0x21, 0xe2, 0x8b, 0x14, 0x71, 0x82, 0xaa, 0x6f, 0xf0, 0xd6, 0xb5, 0x12, 0x04,
	0xd3, 0x76, 0xfd, 0x37, 0xdd, 0xcb, 0x64, 0x9d, 0x2e, 0x50, 0x5f, 0x41, 0xd7, 0x5c, 0x38, 0x6b,
	0x63, 0x12, 0xc7, 0x39, 0x55, 0xce, 0x0f, 0x5b, 0x75, 0x96, 0x86, 0x9c, 0xe4, 0xa9, 0xb3, 0xaf,
	0xb7, 0x35, 0xa3, 0x8d, 0x9b, 0xfc, 0x34, 0xb4, 0xea, 0x3b, 0x4f, 0x15, 0xe4, 0x8b, 0xfc, 0xf8,
	0xa6, 0xfb, 0x11, 0xeb, 0xec, 0x6e, 0x96, 0x3e, 0xc5, 0xa7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0xca, 0xf8, 0x83, 0x35, 0x03, 0x00, 0x00,
}
