// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package com_lending_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	Paid                   bool     `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	DatePaid               string   `protobuf:"bytes,2,opt,name=datePaid,proto3" json:"datePaid,omitempty"`
	LoanNumber             string   `protobuf:"bytes,3,opt,name=loanNumber,proto3" json:"loanNumber,omitempty"`
	AmountInCents          int64    `protobuf:"varint,4,opt,name=amountInCents,proto3" json:"amountInCents,omitempty"`
	SourceAccountNumber    string   `protobuf:"bytes,5,opt,name=sourceAccountNumber,proto3" json:"sourceAccountNumber,omitempty"`
	SourcePaymentNumber    string   `protobuf:"bytes,6,opt,name=sourcePaymentNumber,proto3" json:"sourcePaymentNumber,omitempty"`
	SourceObligationNumber string   `protobuf:"bytes,7,opt,name=sourceObligationNumber,proto3" json:"sourceObligationNumber,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *Payment) GetDatePaid() string {
	if m != nil {
		return m.DatePaid
	}
	return ""
}

func (m *Payment) GetLoanNumber() string {
	if m != nil {
		return m.LoanNumber
	}
	return ""
}

func (m *Payment) GetAmountInCents() int64 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

func (m *Payment) GetSourceAccountNumber() string {
	if m != nil {
		return m.SourceAccountNumber
	}
	return ""
}

func (m *Payment) GetSourcePaymentNumber() string {
	if m != nil {
		return m.SourcePaymentNumber
	}
	return ""
}

func (m *Payment) GetSourceObligationNumber() string {
	if m != nil {
		return m.SourceObligationNumber
	}
	return ""
}

type PaymentList struct {
	Payments             []*Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PaymentList) Reset()         { *m = PaymentList{} }
func (m *PaymentList) String() string { return proto.CompactTextString(m) }
func (*PaymentList) ProtoMessage()    {}
func (*PaymentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *PaymentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentList.Unmarshal(m, b)
}
func (m *PaymentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentList.Marshal(b, m, deterministic)
}
func (m *PaymentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentList.Merge(m, src)
}
func (m *PaymentList) XXX_Size() int {
	return xxx_messageInfo_PaymentList.Size(m)
}
func (m *PaymentList) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentList.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentList proto.InternalMessageInfo

func (m *PaymentList) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func init() {
	proto.RegisterType((*Payment)(nil), "com.lending.proto.Payment")
	proto.RegisterType((*PaymentList)(nil), "com.lending.proto.PaymentList")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xa6, 0x7f, 0xd2, 0x29, 0x3d, 0x38, 0x82, 0x84, 0x1e, 0x24, 0x14, 0x0f, 0x39,
	0x05, 0x51, 0xe8, 0xdd, 0x4a, 0x0f, 0x82, 0x68, 0xc8, 0x1b, 0x6c, 0x92, 0xa5, 0x2c, 0x24, 0x33,
	0x21, 0xbb, 0x11, 0x7c, 0x16, 0x5f, 0x56, 0xba, 0x59, 0x6b, 0x8b, 0xf6, 0xb6, 0xfb, 0xfb, 0xe6,
	0xf7, 0x31, 0x0c, 0x2c, 0x5b, 0xf9, 0xd9, 0x28, 0xb2, 0x69, 0xdb, 0xb1, 0x65, 0xbc, 0x2a, 0xb9,
	0x49, 0x6b, 0x45, 0x95, 0xa6, 0xfd, 0x80, 0xd6, 0x5f, 0x23, 0x98, 0x65, 0xc3, 0x10, 0x22, 0x8c,
	0x5b, 0xa9, 0xab, 0x48, 0xc4, 0x22, 0x09, 0x73, 0xf7, 0xc6, 0x15, 0x84, 0x95, 0xb4, 0x2a, 0x3b,
	0xf0, 0x51, 0x2c, 0x92, 0x79, 0x7e, 0xfc, 0xe3, 0x2d, 0x40, 0xcd, 0x92, 0xde, 0xfa, 0xa6, 0x50,
	0x5d, 0x14, 0xb8, 0xf4, 0x84, 0xe0, 0x1d, 0x2c, 0x65, 0xc3, 0x3d, 0xd9, 0x17, 0x7a, 0x56, 0x64,
	0x4d, 0x34, 0x8e, 0x45, 0x12, 0xe4, 0xe7, 0x10, 0xef, 0xe1, 0xda, 0x70, 0xdf, 0x95, 0xea, 0xa9,
	0x2c, 0x0f, 0xdc, 0xd7, 0x4d, 0x5c, 0xdd, 0x7f, 0xd1, 0xaf, 0xe1, 0x17, 0xf7, 0xc6, 0xf4, 0xd4,
	0x38, 0x8b, 0x70, 0x03, 0x37, 0x03, 0x7e, 0x2f, 0x6a, 0xbd, 0x97, 0x56, 0xf3, 0xcf, 0xd6, 0x33,
	0x27, 0x5d, 0x48, 0xd7, 0x3b, 0x58, 0xf8, 0xa2, 0x57, 0x6d, 0x2c, 0x6e, 0x20, 0xf4, 0x07, 0x35,
	0x91, 0x88, 0x83, 0x64, 0xf1, 0xb0, 0x4a, 0xff, 0x9c, 0x34, 0xf5, 0x46, 0x7e, 0x9c, 0xdd, 0xce,
	0xb7, 0x93, 0x1d, 0xf1, 0x87, 0xcc, 0x44, 0x31, 0x75, 0x33, 0x8f, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x16, 0x2d, 0xb5, 0x54, 0x9a, 0x01, 0x00, 0x00,
}
