// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package com_lending_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	Paid                   bool     `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	DatePaid               string   `protobuf:"bytes,2,opt,name=datePaid,proto3" json:"datePaid,omitempty"`
	LoanNumber             string   `protobuf:"bytes,3,opt,name=loanNumber,proto3" json:"loanNumber,omitempty"`
	AmoutInCents           int64    `protobuf:"varint,4,opt,name=amoutInCents,proto3" json:"amoutInCents,omitempty"`
	SourceAccountNumber    string   `protobuf:"bytes,5,opt,name=sourceAccountNumber,proto3" json:"sourceAccountNumber,omitempty"`
	SourcePaymentNumber    string   `protobuf:"bytes,6,opt,name=sourcePaymentNumber,proto3" json:"sourcePaymentNumber,omitempty"`
	SourceObligationNumber string   `protobuf:"bytes,7,opt,name=sourceObligationNumber,proto3" json:"sourceObligationNumber,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *Payment) GetDatePaid() string {
	if m != nil {
		return m.DatePaid
	}
	return ""
}

func (m *Payment) GetLoanNumber() string {
	if m != nil {
		return m.LoanNumber
	}
	return ""
}

func (m *Payment) GetAmoutInCents() int64 {
	if m != nil {
		return m.AmoutInCents
	}
	return 0
}

func (m *Payment) GetSourceAccountNumber() string {
	if m != nil {
		return m.SourceAccountNumber
	}
	return ""
}

func (m *Payment) GetSourcePaymentNumber() string {
	if m != nil {
		return m.SourcePaymentNumber
	}
	return ""
}

func (m *Payment) GetSourceObligationNumber() string {
	if m != nil {
		return m.SourceObligationNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "com.lending.proto.Payment")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4a, 0xc7, 0x30,
	0x10, 0x80, 0xc9, 0xef, 0x7f, 0x0f, 0x1d, 0x3c, 0x41, 0x8a, 0x83, 0x94, 0x4e, 0x9d, 0x8a, 0x20,
	0xb8, 0x5b, 0x71, 0x70, 0xd1, 0xd2, 0x37, 0x48, 0xd3, 0x50, 0x02, 0xcd, 0x5d, 0x69, 0x13, 0xc1,
	0x47, 0xf1, 0x6d, 0xc5, 0xb4, 0x6a, 0x0b, 0xba, 0x25, 0xdf, 0x97, 0xef, 0x38, 0x02, 0xe7, 0xbd,
	0x7c, 0xb7, 0x9a, 0x5c, 0xde, 0x0f, 0xec, 0x18, 0x2f, 0x14, 0xdb, 0xbc, 0xd3, 0xd4, 0x18, 0x6a,
	0x27, 0x94, 0x7e, 0x6c, 0xe0, 0x58, 0x4e, 0x8f, 0x10, 0x61, 0xd7, 0x4b, 0xd3, 0xc4, 0x22, 0x11,
	0xd9, 0xa9, 0x0a, 0x67, 0xbc, 0x86, 0x53, 0x23, 0x9d, 0x2e, 0xbf, 0xf8, 0x26, 0x11, 0x59, 0x54,
	0xfd, 0xdc, 0xf1, 0x06, 0xa0, 0x63, 0x49, 0x2f, 0xde, 0xd6, 0x7a, 0x88, 0xb7, 0xc1, 0x2e, 0x08,
	0xa6, 0x70, 0x26, 0x2d, 0x7b, 0xf7, 0x4c, 0x8f, 0x9a, 0xdc, 0x18, 0xef, 0x12, 0x91, 0x6d, 0xab,
	0x15, 0xc3, 0x5b, 0xb8, 0x1c, 0xd9, 0x0f, 0x4a, 0x3f, 0x28, 0xc5, 0x9e, 0xdc, 0x3c, 0x6c, 0x1f,
	0x86, 0xfd, 0xa5, 0x7e, 0x8b, 0x79, 0xed, 0xb9, 0x38, 0x2c, 0x8b, 0x95, 0xc2, 0x7b, 0xb8, 0x9a,
	0xf0, 0x6b, 0xdd, 0x99, 0x56, 0x3a, 0xc3, 0xdf, 0x3b, 0x1f, 0x43, 0xf4, 0x8f, 0x2d, 0xa2, 0x62,
	0xff, 0x44, 0xfc, 0x26, 0x4b, 0x51, 0x1f, 0xc2, 0x6f, 0xdd, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xdb, 0x93, 0x77, 0x41, 0x51, 0x01, 0x00, 0x00,
}
