// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prospect.proto

package com_lending_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prospect struct {
	ProspectId int64 `protobuf:"varint,1,opt,name=prospectId,proto3" json:"prospectId,omitempty"`
	// Types that are valid to be assigned to ProspectType:
	//	*Prospect_Business
	//	*Prospect_Person
	ProspectType         isProspect_ProspectType `protobuf_oneof:"prospectType"`
	AnyProspect          *any.Any                `protobuf:"bytes,4,opt,name=anyProspect,proto3" json:"anyProspect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Prospect) Reset()         { *m = Prospect{} }
func (m *Prospect) String() string { return proto.CompactTextString(m) }
func (*Prospect) ProtoMessage()    {}
func (*Prospect) Descriptor() ([]byte, []int) {
	return fileDescriptor_51574949aab27482, []int{0}
}

func (m *Prospect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prospect.Unmarshal(m, b)
}
func (m *Prospect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prospect.Marshal(b, m, deterministic)
}
func (m *Prospect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prospect.Merge(m, src)
}
func (m *Prospect) XXX_Size() int {
	return xxx_messageInfo_Prospect.Size(m)
}
func (m *Prospect) XXX_DiscardUnknown() {
	xxx_messageInfo_Prospect.DiscardUnknown(m)
}

var xxx_messageInfo_Prospect proto.InternalMessageInfo

func (m *Prospect) GetProspectId() int64 {
	if m != nil {
		return m.ProspectId
	}
	return 0
}

type isProspect_ProspectType interface {
	isProspect_ProspectType()
}

type Prospect_Business struct {
	Business *Business `protobuf:"bytes,2,opt,name=business,proto3,oneof"`
}

type Prospect_Person struct {
	Person *Person `protobuf:"bytes,3,opt,name=person,proto3,oneof"`
}

func (*Prospect_Business) isProspect_ProspectType() {}

func (*Prospect_Person) isProspect_ProspectType() {}

func (m *Prospect) GetProspectType() isProspect_ProspectType {
	if m != nil {
		return m.ProspectType
	}
	return nil
}

func (m *Prospect) GetBusiness() *Business {
	if x, ok := m.GetProspectType().(*Prospect_Business); ok {
		return x.Business
	}
	return nil
}

func (m *Prospect) GetPerson() *Person {
	if x, ok := m.GetProspectType().(*Prospect_Person); ok {
		return x.Person
	}
	return nil
}

func (m *Prospect) GetAnyProspect() *any.Any {
	if m != nil {
		return m.AnyProspect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Prospect) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Prospect_Business)(nil),
		(*Prospect_Person)(nil),
	}
}

type Business struct {
	BusinessId           int64    `protobuf:"varint,1,opt,name=businessId,proto3" json:"businessId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Naics                string   `protobuf:"bytes,3,opt,name=naics,proto3" json:"naics,omitempty"`
	Fein                 string   `protobuf:"bytes,4,opt,name=fein,proto3" json:"fein,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Business) Reset()         { *m = Business{} }
func (m *Business) String() string { return proto.CompactTextString(m) }
func (*Business) ProtoMessage()    {}
func (*Business) Descriptor() ([]byte, []int) {
	return fileDescriptor_51574949aab27482, []int{1}
}

func (m *Business) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Business.Unmarshal(m, b)
}
func (m *Business) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Business.Marshal(b, m, deterministic)
}
func (m *Business) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Business.Merge(m, src)
}
func (m *Business) XXX_Size() int {
	return xxx_messageInfo_Business.Size(m)
}
func (m *Business) XXX_DiscardUnknown() {
	xxx_messageInfo_Business.DiscardUnknown(m)
}

var xxx_messageInfo_Business proto.InternalMessageInfo

func (m *Business) GetBusinessId() int64 {
	if m != nil {
		return m.BusinessId
	}
	return 0
}

func (m *Business) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Business) GetNaics() string {
	if m != nil {
		return m.Naics
	}
	return ""
}

func (m *Business) GetFein() string {
	if m != nil {
		return m.Fein
	}
	return ""
}

type Person struct {
	PersonId             int64    `protobuf:"varint,1,opt,name=personId,proto3" json:"personId,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	GovernmentId         string   `protobuf:"bytes,4,opt,name=governmentId,proto3" json:"governmentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_51574949aab27482, []int{2}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetPersonId() int64 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetGovernmentId() string {
	if m != nil {
		return m.GovernmentId
	}
	return ""
}

func init() {
	proto.RegisterType((*Prospect)(nil), "com.lending.proto.Prospect")
	proto.RegisterType((*Business)(nil), "com.lending.proto.Business")
	proto.RegisterType((*Person)(nil), "com.lending.proto.Person")
}

func init() { proto.RegisterFile("prospect.proto", fileDescriptor_51574949aab27482) }

var fileDescriptor_51574949aab27482 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x6b, 0x83, 0x30,
	0x18, 0x6d, 0xda, 0xae, 0xe8, 0xd7, 0x52, 0x58, 0xe8, 0xc1, 0x76, 0x63, 0x14, 0x4f, 0x3d, 0xa5,
	0xb0, 0xc2, 0x60, 0xc7, 0xf5, 0xd4, 0x5d, 0x86, 0x84, 0xfd, 0x01, 0xb5, 0xd1, 0x09, 0xfa, 0x45,
	0x8c, 0x1d, 0x78, 0xdd, 0x4f, 0xdd, 0x2f, 0x19, 0x26, 0x46, 0x3b, 0xb6, 0x5b, 0xde, 0xcb, 0x7b,
	0x79, 0xef, 0x29, 0x2c, 0xcb, 0x4a, 0xaa, 0x52, 0xc4, 0x35, 0x2b, 0x2b, 0x59, 0x4b, 0x7a, 0x1b,
	0xcb, 0x82, 0xe5, 0x02, 0xcf, 0x19, 0xa6, 0x86, 0xda, 0xac, 0x53, 0x29, 0xd3, 0x5c, 0xec, 0x35,
	0x8a, 0x2e, 0xc9, 0x3e, 0xc4, 0xc6, 0x5c, 0xf9, 0xdf, 0x04, 0x9c, 0xa0, 0x7b, 0x80, 0x3e, 0x00,
	0xd8, 0xc7, 0x5e, 0xcf, 0x1e, 0xd9, 0x92, 0xdd, 0x84, 0x5f, 0x31, 0xf4, 0x19, 0x9c, 0xe8, 0xa2,
	0x32, 0x14, 0x4a, 0x79, 0xe3, 0x2d, 0xd9, 0xcd, 0x1f, 0xef, 0xd8, 0x9f, 0x34, 0x76, 0xec, 0x24,
	0xa7, 0x11, 0xef, 0xe5, 0xf4, 0x00, 0xb3, 0x52, 0x54, 0x4a, 0xa2, 0x37, 0xd1, 0xc6, 0xf5, 0x3f,
	0xc6, 0x40, 0x0b, 0x4e, 0x23, 0xde, 0x49, 0xe9, 0x13, 0xcc, 0x43, 0x6c, 0x6c, 0x3d, 0x6f, 0xaa,
	0x9d, 0x2b, 0x66, 0xd6, 0x30, 0xbb, 0x86, 0xbd, 0x60, 0xc3, 0xaf, 0x85, 0xc7, 0x25, 0x2c, 0x6c,
	0xeb, 0xf7, 0xa6, 0x14, 0xfe, 0x07, 0x38, 0xb6, 0x54, 0xbb, 0xd1, 0x96, 0x1a, 0x36, 0x0e, 0x0c,
	0xa5, 0x30, 0xc5, 0xb0, 0x10, 0x7a, 0x9f, 0xcb, 0xf5, 0x99, 0xae, 0xe0, 0x06, 0xc3, 0x2c, 0x56,
	0xba, 0xbb, 0xcb, 0x0d, 0x68, 0x95, 0x89, 0xc8, 0x50, 0xd7, 0x72, 0xb9, 0x3e, 0xfb, 0x5f, 0x04,
	0x66, 0x66, 0x06, 0xdd, 0x80, 0x63, 0x66, 0xf4, 0x31, 0x3d, 0xa6, 0xf7, 0xe0, 0x26, 0x59, 0xa5,
	0xea, 0xb7, 0x21, 0x69, 0x20, 0x5a, 0x67, 0x1e, 0x76, 0x97, 0x26, 0xb1, 0xc7, 0xd4, 0x87, 0x45,
	0x2a, 0x3f, 0x45, 0x85, 0x85, 0xc0, 0xf6, 0x27, 0x99, 0xf0, 0x5f, 0xdc, 0x71, 0x1c, 0x90, 0x68,
	0xa6, 0xbf, 0xce, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x33, 0x77, 0xa7, 0x68, 0x1e, 0x02, 0x00,
	0x00,
}
