version: '3.4'

services:
  json-generator:
    build: ./docker/json-gen
    image: json-data-generator
    container_name: json-gen
    volumes:
      - ./docker/json-gen/logs:/json-data-generator/logs
      - ./docker/json-gen/conf:/json-data-generator/conf
    networks:
      - protobuf_poc_protobuf
    tty: true

  protos:
    build:
      context: ./domain-protos
      dockerfile: Dockerfile
    image: domain_protos
    command: ["/bin/true"]

  loan:
    build:
      context: ./svc-loan
      dockerfile: Dockerfile
    image: svc-loan
    container_name: svc-loan
    depends_on:
      - protos
    ports:
      - 8000:8080
    networks:
      - protobuf_poc_protobuf
    environment:
      - KAFKA_BROKER_URL=kafka:29092
    tty: true

  aggregator:
    build:
      context: ./svc-aggregator
      dockerfile: Dockerfile
    image: svc-aggregator
    ports:
      - 9000:9000
    container_name: svc-aggregator
    networks:
      - protobuf_poc_protobuf
    environment:
      - KAFKA_BROKER_URI=kafka:29092
      - LOAN_TOPIC_NAME=loan
      - PAYMENT_TOPIC_NAME=payment
    tty: true

  payment:
    build:
      context: ./svc-payment
      dockerfile: Dockerfile
    image: svc-payment
    container_name: svc-payment
    networks:
      - protobuf_poc_protobuf
    ports:
      - 3000:3000
    environment:
      - KAFKA_BROKER_ADDR=kafka:29092
      - GET_LOAN_URL=http://loan:8000/loan/
    tty: true

  loan_consumer:
    build:
      context: ./svc-payment
      dockerfile: Dockerfile
    image: svc-payment
    container_name: racecar_loan_consumer
    command: ["bundle", "exec", "racecar", "LoanConsumer"]
    networks:
      - protobuf_poc_protobuf
    environment:
      - KAFKA_BROKER_ADDR=kafka:29092
      - LOAN_TOPIC_CONSUME=loan
    tty: true

  payment_producer:
    build:
      context: ./svc-payment
      dockerfile: Dockerfile
    image: svc-payment
    container_name: racecar_payment_producer
    command: ["bundle", "exec", "racecar", "PaymentProducer"]
    networks:
      - protobuf_poc_protobuf
    environment:
      - KAFKA_BROKER_ADDR=kafka:29092
      - PAYMENT_TOPIC_CONSUME=payment_intake
      - PAYMENT_TOPIC_PRODUCE=payment
    tty: true

networks:
  protobuf_poc_protobuf:
    external: true
