version: '3.4'

services:
  json-generator:
    build: ./docker/json-gen
    image: json-data-generator
    container_name: json-gen
    volumes:
      - ./docker/json-gen/logs:/json-data-generator/logs
      - ./docker/json-gen/conf:/json-data-generator/conf
    networks:
      - protobuf_poc_protobuf
    tty: true

  loan:
    build:
      context: ./svc-loan
      dockerfile: Dockerfile
    image: svc-loan
    container_name: svc-loan
    ports:
      - 8000:8080
    networks:
      - protobuf_poc_protobuf
    environment:
      - KAFKA_BROKER_URL=kafka:29092
    tty: true

  # aggregator:
  #   build:
  #     context: ./svc-aggregator
  #     dockerfile: Dockerfile
  #   image: svc-aggregator
  #   container_name: svc-aggregator
  #   networks:
  #     - protobuf_poc_protobuf
  #   environment:
  #     - KAFKA_BROKER_URI=kafka:29092
  #     - LOAN_TOPIC_NAME=loan
  #     - PAYMENT_TOPIC_NAME=payment
  #   tty: true

networks:
  protobuf_poc_protobuf:
    external: true
