// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/prospect.proto

package com.lending.proto;

public interface BusinessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lending.proto.Business)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 businessId = 1;</code>
   */
  long getBusinessId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string naics = 3;</code>
   */
  java.lang.String getNaics();
  /**
   * <code>string naics = 3;</code>
   */
  com.google.protobuf.ByteString
      getNaicsBytes();

  /**
   * <code>string fein = 4;</code>
   */
  java.lang.String getFein();
  /**
   * <code>string fein = 4;</code>
   */
  com.google.protobuf.ByteString
      getFeinBytes();
}
