// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/payment.proto

package com.lending.proto;

public final class Enova {
  private Enova() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lending_proto_Payment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lending_proto_Payment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/payment.proto\022\021com.lending.prot" +
      "o\"\255\001\n\007Payment\022\014\n\004paid\030\001 \001(\010\022\020\n\010datePaid\030" +
      "\002 \001(\t\022\022\n\nloanNumber\030\003 \001(\t\022\024\n\014amoutInCent" +
      "s\030\004 \001(\003\022\033\n\023sourceAccountNumber\030\005 \001(\t\022\033\n\023" +
      "sourcePaymentNumber\030\006 \001(\t\022\036\n\026sourceOblig" +
      "ationNumber\030\007 \001(\tB\tB\005EnovaP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lending_proto_Payment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lending_proto_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lending_proto_Payment_descriptor,
        new java.lang.String[] { "Paid", "DatePaid", "LoanNumber", "AmoutInCents", "SourceAccountNumber", "SourcePaymentNumber", "SourceObligationNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
