// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/loan.proto

package com.lending.proto;

public final class Lending {
  private Lending() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lending_proto_Loan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lending_proto_Loan_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021protos/loan.proto\022\021com.lending.proto\"\306" +
      "\003\n\004Loan\022\016\n\006status\030\001 \001(\t\022\021\n\tcalledDue\030\002 \001" +
      "(\010\022\022\n\ndateClosed\030\003 \001(\t\022\022\n\ndateOpened\030\004 \001" +
      "(\t\022\022\n\nloanNumber\030\005 \001(\t\022\023\n\013daysPastDue\030\006 " +
      "\001(\003\022\024\n\014currentOwner\030\007 \001(\t\022\024\n\014transferFro" +
      "m\030\010 \001(\t\022\033\n\023sourceAccountNumber\030\t \001(\t\022\034\n\024" +
      "amountPastDueInCents\030\n \001(\003\022\035\n\025currentBal" +
      "anceInCents\030\013 \001(\003\022\035\n\025lastPaymentContinge" +
      "nt\030\014 \001(\010\022\035\n\025transferEffectiveDate\030\r \001(\t\022" +
      "\036\n\026calledDueAmountInCents\030\016 \001(\003\022!\n\031outst",
      "andingBalanceInCents\030\017 \001(\003\022 \n\030inCollecti" +
      "onBeforeClosed\030\021 \001(\010\022!\n\031originalLoanAmou" +
      "ntInCents\030\022 \001(\003B\013B\007LendingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lending_proto_Loan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lending_proto_Loan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lending_proto_Loan_descriptor,
        new java.lang.String[] { "Status", "CalledDue", "DateClosed", "DateOpened", "LoanNumber", "DaysPastDue", "CurrentOwner", "TransferFrom", "SourceAccountNumber", "AmountPastDueInCents", "CurrentBalanceInCents", "LastPaymentContingent", "TransferEffectiveDate", "CalledDueAmountInCents", "OutstandingBalanceInCents", "InCollectionBeforeClosed", "OriginalLoanAmountInCents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
