// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/payment.proto

package com.lending.proto;

public interface PaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lending.proto.Payment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool paid = 1;</code>
   */
  boolean getPaid();

  /**
   * <code>string datePaid = 2;</code>
   */
  java.lang.String getDatePaid();
  /**
   * <code>string datePaid = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatePaidBytes();

  /**
   * <code>string loanNumber = 3;</code>
   */
  java.lang.String getLoanNumber();
  /**
   * <code>string loanNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getLoanNumberBytes();

  /**
   * <code>int64 amountInCents = 4;</code>
   */
  long getAmountInCents();

  /**
   * <code>string sourceAccountNumber = 5;</code>
   */
  java.lang.String getSourceAccountNumber();
  /**
   * <code>string sourceAccountNumber = 5;</code>
   */
  com.google.protobuf.ByteString
      getSourceAccountNumberBytes();

  /**
   * <code>string sourcePaymentNumber = 6;</code>
   */
  java.lang.String getSourcePaymentNumber();
  /**
   * <code>string sourcePaymentNumber = 6;</code>
   */
  com.google.protobuf.ByteString
      getSourcePaymentNumberBytes();

  /**
   * <code>string sourceObligationNumber = 7;</code>
   */
  java.lang.String getSourceObligationNumber();
  /**
   * <code>string sourceObligationNumber = 7;</code>
   */
  com.google.protobuf.ByteString
      getSourceObligationNumberBytes();
}
