// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/payment.proto

package com.lending.proto;

public interface PaymentListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lending.proto.PaymentList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.lending.proto.Payment payments = 1;</code>
   */
  java.util.List<com.lending.proto.Payment> 
      getPaymentsList();
  /**
   * <code>repeated .com.lending.proto.Payment payments = 1;</code>
   */
  com.lending.proto.Payment getPayments(int index);
  /**
   * <code>repeated .com.lending.proto.Payment payments = 1;</code>
   */
  int getPaymentsCount();
  /**
   * <code>repeated .com.lending.proto.Payment payments = 1;</code>
   */
  java.util.List<? extends com.lending.proto.PaymentOrBuilder> 
      getPaymentsOrBuilderList();
  /**
   * <code>repeated .com.lending.proto.Payment payments = 1;</code>
   */
  com.lending.proto.PaymentOrBuilder getPaymentsOrBuilder(
      int index);
}
