// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/payment.proto

package com.lending.proto;

/**
 * Protobuf type {@code com.lending.proto.Payment}
 */
public  final class Payment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lending.proto.Payment)
    PaymentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Payment.newBuilder() to construct.
  private Payment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payment() {
    paid_ = false;
    datePaid_ = "";
    loanNumber_ = "";
    amountInCents_ = 0L;
    sourceAccountNumber_ = "";
    sourcePaymentNumber_ = "";
    sourceObligationNumber_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Payment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            paid_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            datePaid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            loanNumber_ = s;
            break;
          }
          case 32: {

            amountInCents_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceAccountNumber_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            sourcePaymentNumber_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceObligationNumber_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lending.proto.Enova.internal_static_com_lending_proto_Payment_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lending.proto.Enova.internal_static_com_lending_proto_Payment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lending.proto.Payment.class, com.lending.proto.Payment.Builder.class);
  }

  public static final int PAID_FIELD_NUMBER = 1;
  private boolean paid_;
  /**
   * <code>bool paid = 1;</code>
   */
  public boolean getPaid() {
    return paid_;
  }

  public static final int DATEPAID_FIELD_NUMBER = 2;
  private volatile java.lang.Object datePaid_;
  /**
   * <code>string datePaid = 2;</code>
   */
  public java.lang.String getDatePaid() {
    java.lang.Object ref = datePaid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datePaid_ = s;
      return s;
    }
  }
  /**
   * <code>string datePaid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDatePaidBytes() {
    java.lang.Object ref = datePaid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datePaid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOANNUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object loanNumber_;
  /**
   * <code>string loanNumber = 3;</code>
   */
  public java.lang.String getLoanNumber() {
    java.lang.Object ref = loanNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loanNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string loanNumber = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLoanNumberBytes() {
    java.lang.Object ref = loanNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loanNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNTINCENTS_FIELD_NUMBER = 4;
  private long amountInCents_;
  /**
   * <code>int64 amountInCents = 4;</code>
   */
  public long getAmountInCents() {
    return amountInCents_;
  }

  public static final int SOURCEACCOUNTNUMBER_FIELD_NUMBER = 5;
  private volatile java.lang.Object sourceAccountNumber_;
  /**
   * <code>string sourceAccountNumber = 5;</code>
   */
  public java.lang.String getSourceAccountNumber() {
    java.lang.Object ref = sourceAccountNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceAccountNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceAccountNumber = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSourceAccountNumberBytes() {
    java.lang.Object ref = sourceAccountNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceAccountNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEPAYMENTNUMBER_FIELD_NUMBER = 6;
  private volatile java.lang.Object sourcePaymentNumber_;
  /**
   * <code>string sourcePaymentNumber = 6;</code>
   */
  public java.lang.String getSourcePaymentNumber() {
    java.lang.Object ref = sourcePaymentNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourcePaymentNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string sourcePaymentNumber = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSourcePaymentNumberBytes() {
    java.lang.Object ref = sourcePaymentNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourcePaymentNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEOBLIGATIONNUMBER_FIELD_NUMBER = 7;
  private volatile java.lang.Object sourceObligationNumber_;
  /**
   * <code>string sourceObligationNumber = 7;</code>
   */
  public java.lang.String getSourceObligationNumber() {
    java.lang.Object ref = sourceObligationNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceObligationNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceObligationNumber = 7;</code>
   */
  public com.google.protobuf.ByteString
      getSourceObligationNumberBytes() {
    java.lang.Object ref = sourceObligationNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceObligationNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (paid_ != false) {
      output.writeBool(1, paid_);
    }
    if (!getDatePaidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datePaid_);
    }
    if (!getLoanNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, loanNumber_);
    }
    if (amountInCents_ != 0L) {
      output.writeInt64(4, amountInCents_);
    }
    if (!getSourceAccountNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sourceAccountNumber_);
    }
    if (!getSourcePaymentNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sourcePaymentNumber_);
    }
    if (!getSourceObligationNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sourceObligationNumber_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (paid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, paid_);
    }
    if (!getDatePaidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datePaid_);
    }
    if (!getLoanNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, loanNumber_);
    }
    if (amountInCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, amountInCents_);
    }
    if (!getSourceAccountNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sourceAccountNumber_);
    }
    if (!getSourcePaymentNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sourcePaymentNumber_);
    }
    if (!getSourceObligationNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sourceObligationNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lending.proto.Payment)) {
      return super.equals(obj);
    }
    com.lending.proto.Payment other = (com.lending.proto.Payment) obj;

    boolean result = true;
    result = result && (getPaid()
        == other.getPaid());
    result = result && getDatePaid()
        .equals(other.getDatePaid());
    result = result && getLoanNumber()
        .equals(other.getLoanNumber());
    result = result && (getAmountInCents()
        == other.getAmountInCents());
    result = result && getSourceAccountNumber()
        .equals(other.getSourceAccountNumber());
    result = result && getSourcePaymentNumber()
        .equals(other.getSourcePaymentNumber());
    result = result && getSourceObligationNumber()
        .equals(other.getSourceObligationNumber());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPaid());
    hash = (37 * hash) + DATEPAID_FIELD_NUMBER;
    hash = (53 * hash) + getDatePaid().hashCode();
    hash = (37 * hash) + LOANNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLoanNumber().hashCode();
    hash = (37 * hash) + AMOUNTINCENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmountInCents());
    hash = (37 * hash) + SOURCEACCOUNTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSourceAccountNumber().hashCode();
    hash = (37 * hash) + SOURCEPAYMENTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSourcePaymentNumber().hashCode();
    hash = (37 * hash) + SOURCEOBLIGATIONNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSourceObligationNumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lending.proto.Payment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Payment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Payment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Payment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Payment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Payment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Payment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lending.proto.Payment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lending.proto.Payment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lending.proto.Payment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lending.proto.Payment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lending.proto.Payment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lending.proto.Payment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lending.proto.Payment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lending.proto.Payment)
      com.lending.proto.PaymentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lending.proto.Enova.internal_static_com_lending_proto_Payment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lending.proto.Enova.internal_static_com_lending_proto_Payment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lending.proto.Payment.class, com.lending.proto.Payment.Builder.class);
    }

    // Construct using com.lending.proto.Payment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      paid_ = false;

      datePaid_ = "";

      loanNumber_ = "";

      amountInCents_ = 0L;

      sourceAccountNumber_ = "";

      sourcePaymentNumber_ = "";

      sourceObligationNumber_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lending.proto.Enova.internal_static_com_lending_proto_Payment_descriptor;
    }

    public com.lending.proto.Payment getDefaultInstanceForType() {
      return com.lending.proto.Payment.getDefaultInstance();
    }

    public com.lending.proto.Payment build() {
      com.lending.proto.Payment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lending.proto.Payment buildPartial() {
      com.lending.proto.Payment result = new com.lending.proto.Payment(this);
      result.paid_ = paid_;
      result.datePaid_ = datePaid_;
      result.loanNumber_ = loanNumber_;
      result.amountInCents_ = amountInCents_;
      result.sourceAccountNumber_ = sourceAccountNumber_;
      result.sourcePaymentNumber_ = sourcePaymentNumber_;
      result.sourceObligationNumber_ = sourceObligationNumber_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lending.proto.Payment) {
        return mergeFrom((com.lending.proto.Payment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lending.proto.Payment other) {
      if (other == com.lending.proto.Payment.getDefaultInstance()) return this;
      if (other.getPaid() != false) {
        setPaid(other.getPaid());
      }
      if (!other.getDatePaid().isEmpty()) {
        datePaid_ = other.datePaid_;
        onChanged();
      }
      if (!other.getLoanNumber().isEmpty()) {
        loanNumber_ = other.loanNumber_;
        onChanged();
      }
      if (other.getAmountInCents() != 0L) {
        setAmountInCents(other.getAmountInCents());
      }
      if (!other.getSourceAccountNumber().isEmpty()) {
        sourceAccountNumber_ = other.sourceAccountNumber_;
        onChanged();
      }
      if (!other.getSourcePaymentNumber().isEmpty()) {
        sourcePaymentNumber_ = other.sourcePaymentNumber_;
        onChanged();
      }
      if (!other.getSourceObligationNumber().isEmpty()) {
        sourceObligationNumber_ = other.sourceObligationNumber_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lending.proto.Payment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lending.proto.Payment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean paid_ ;
    /**
     * <code>bool paid = 1;</code>
     */
    public boolean getPaid() {
      return paid_;
    }
    /**
     * <code>bool paid = 1;</code>
     */
    public Builder setPaid(boolean value) {
      
      paid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool paid = 1;</code>
     */
    public Builder clearPaid() {
      
      paid_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object datePaid_ = "";
    /**
     * <code>string datePaid = 2;</code>
     */
    public java.lang.String getDatePaid() {
      java.lang.Object ref = datePaid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datePaid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string datePaid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDatePaidBytes() {
      java.lang.Object ref = datePaid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datePaid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datePaid = 2;</code>
     */
    public Builder setDatePaid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datePaid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string datePaid = 2;</code>
     */
    public Builder clearDatePaid() {
      
      datePaid_ = getDefaultInstance().getDatePaid();
      onChanged();
      return this;
    }
    /**
     * <code>string datePaid = 2;</code>
     */
    public Builder setDatePaidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datePaid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object loanNumber_ = "";
    /**
     * <code>string loanNumber = 3;</code>
     */
    public java.lang.String getLoanNumber() {
      java.lang.Object ref = loanNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loanNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string loanNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLoanNumberBytes() {
      java.lang.Object ref = loanNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loanNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string loanNumber = 3;</code>
     */
    public Builder setLoanNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loanNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string loanNumber = 3;</code>
     */
    public Builder clearLoanNumber() {
      
      loanNumber_ = getDefaultInstance().getLoanNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string loanNumber = 3;</code>
     */
    public Builder setLoanNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loanNumber_ = value;
      onChanged();
      return this;
    }

    private long amountInCents_ ;
    /**
     * <code>int64 amountInCents = 4;</code>
     */
    public long getAmountInCents() {
      return amountInCents_;
    }
    /**
     * <code>int64 amountInCents = 4;</code>
     */
    public Builder setAmountInCents(long value) {
      
      amountInCents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amountInCents = 4;</code>
     */
    public Builder clearAmountInCents() {
      
      amountInCents_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sourceAccountNumber_ = "";
    /**
     * <code>string sourceAccountNumber = 5;</code>
     */
    public java.lang.String getSourceAccountNumber() {
      java.lang.Object ref = sourceAccountNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceAccountNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceAccountNumber = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSourceAccountNumberBytes() {
      java.lang.Object ref = sourceAccountNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceAccountNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceAccountNumber = 5;</code>
     */
    public Builder setSourceAccountNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceAccountNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceAccountNumber = 5;</code>
     */
    public Builder clearSourceAccountNumber() {
      
      sourceAccountNumber_ = getDefaultInstance().getSourceAccountNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceAccountNumber = 5;</code>
     */
    public Builder setSourceAccountNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceAccountNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourcePaymentNumber_ = "";
    /**
     * <code>string sourcePaymentNumber = 6;</code>
     */
    public java.lang.String getSourcePaymentNumber() {
      java.lang.Object ref = sourcePaymentNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourcePaymentNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourcePaymentNumber = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSourcePaymentNumberBytes() {
      java.lang.Object ref = sourcePaymentNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourcePaymentNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourcePaymentNumber = 6;</code>
     */
    public Builder setSourcePaymentNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourcePaymentNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourcePaymentNumber = 6;</code>
     */
    public Builder clearSourcePaymentNumber() {
      
      sourcePaymentNumber_ = getDefaultInstance().getSourcePaymentNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string sourcePaymentNumber = 6;</code>
     */
    public Builder setSourcePaymentNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourcePaymentNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceObligationNumber_ = "";
    /**
     * <code>string sourceObligationNumber = 7;</code>
     */
    public java.lang.String getSourceObligationNumber() {
      java.lang.Object ref = sourceObligationNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceObligationNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceObligationNumber = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSourceObligationNumberBytes() {
      java.lang.Object ref = sourceObligationNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceObligationNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceObligationNumber = 7;</code>
     */
    public Builder setSourceObligationNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceObligationNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceObligationNumber = 7;</code>
     */
    public Builder clearSourceObligationNumber() {
      
      sourceObligationNumber_ = getDefaultInstance().getSourceObligationNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceObligationNumber = 7;</code>
     */
    public Builder setSourceObligationNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceObligationNumber_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lending.proto.Payment)
  }

  // @@protoc_insertion_point(class_scope:com.lending.proto.Payment)
  private static final com.lending.proto.Payment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lending.proto.Payment();
  }

  public static com.lending.proto.Payment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payment>
      PARSER = new com.google.protobuf.AbstractParser<Payment>() {
    public Payment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Payment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payment> getParserForType() {
    return PARSER;
  }

  public com.lending.proto.Payment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

