// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/prospect.proto

package com.lending.proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lending.proto.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 personId = 1;</code>
   */
  long getPersonId();

  /**
   * <code>string firstName = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string governmentId = 4;</code>
   */
  java.lang.String getGovernmentId();
  /**
   * <code>string governmentId = 4;</code>
   */
  com.google.protobuf.ByteString
      getGovernmentIdBytes();
}
