// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/prospect.proto

package com.lending.proto;

/**
 * Protobuf type {@code com.lending.proto.Prospect}
 */
public  final class Prospect extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lending.proto.Prospect)
    ProspectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Prospect.newBuilder() to construct.
  private Prospect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Prospect() {
    prospectId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Prospect(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            prospectId_ = input.readInt64();
            break;
          }
          case 18: {
            com.lending.proto.Business.Builder subBuilder = null;
            if (prospectTypeCase_ == 2) {
              subBuilder = ((com.lending.proto.Business) prospectType_).toBuilder();
            }
            prospectType_ =
                input.readMessage(com.lending.proto.Business.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.lending.proto.Business) prospectType_);
              prospectType_ = subBuilder.buildPartial();
            }
            prospectTypeCase_ = 2;
            break;
          }
          case 26: {
            com.lending.proto.Person.Builder subBuilder = null;
            if (prospectTypeCase_ == 3) {
              subBuilder = ((com.lending.proto.Person) prospectType_).toBuilder();
            }
            prospectType_ =
                input.readMessage(com.lending.proto.Person.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.lending.proto.Person) prospectType_);
              prospectType_ = subBuilder.buildPartial();
            }
            prospectTypeCase_ = 3;
            break;
          }
          case 34: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (anyProspect_ != null) {
              subBuilder = anyProspect_.toBuilder();
            }
            anyProspect_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(anyProspect_);
              anyProspect_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lending.proto.ProspectOuterClass.internal_static_com_lending_proto_Prospect_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lending.proto.ProspectOuterClass.internal_static_com_lending_proto_Prospect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lending.proto.Prospect.class, com.lending.proto.Prospect.Builder.class);
  }

  private int prospectTypeCase_ = 0;
  private java.lang.Object prospectType_;
  public enum ProspectTypeCase
      implements com.google.protobuf.Internal.EnumLite {
    BUSINESS(2),
    PERSON(3),
    PROSPECTTYPE_NOT_SET(0);
    private final int value;
    private ProspectTypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProspectTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ProspectTypeCase forNumber(int value) {
      switch (value) {
        case 2: return BUSINESS;
        case 3: return PERSON;
        case 0: return PROSPECTTYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ProspectTypeCase
  getProspectTypeCase() {
    return ProspectTypeCase.forNumber(
        prospectTypeCase_);
  }

  public static final int PROSPECTID_FIELD_NUMBER = 1;
  private long prospectId_;
  /**
   * <code>int64 prospectId = 1;</code>
   */
  public long getProspectId() {
    return prospectId_;
  }

  public static final int BUSINESS_FIELD_NUMBER = 2;
  /**
   * <code>.com.lending.proto.Business business = 2;</code>
   */
  public boolean hasBusiness() {
    return prospectTypeCase_ == 2;
  }
  /**
   * <code>.com.lending.proto.Business business = 2;</code>
   */
  public com.lending.proto.Business getBusiness() {
    if (prospectTypeCase_ == 2) {
       return (com.lending.proto.Business) prospectType_;
    }
    return com.lending.proto.Business.getDefaultInstance();
  }
  /**
   * <code>.com.lending.proto.Business business = 2;</code>
   */
  public com.lending.proto.BusinessOrBuilder getBusinessOrBuilder() {
    if (prospectTypeCase_ == 2) {
       return (com.lending.proto.Business) prospectType_;
    }
    return com.lending.proto.Business.getDefaultInstance();
  }

  public static final int PERSON_FIELD_NUMBER = 3;
  /**
   * <code>.com.lending.proto.Person person = 3;</code>
   */
  public boolean hasPerson() {
    return prospectTypeCase_ == 3;
  }
  /**
   * <code>.com.lending.proto.Person person = 3;</code>
   */
  public com.lending.proto.Person getPerson() {
    if (prospectTypeCase_ == 3) {
       return (com.lending.proto.Person) prospectType_;
    }
    return com.lending.proto.Person.getDefaultInstance();
  }
  /**
   * <code>.com.lending.proto.Person person = 3;</code>
   */
  public com.lending.proto.PersonOrBuilder getPersonOrBuilder() {
    if (prospectTypeCase_ == 3) {
       return (com.lending.proto.Person) prospectType_;
    }
    return com.lending.proto.Person.getDefaultInstance();
  }

  public static final int ANYPROSPECT_FIELD_NUMBER = 4;
  private com.google.protobuf.Any anyProspect_;
  /**
   * <code>.google.protobuf.Any anyProspect = 4;</code>
   */
  public boolean hasAnyProspect() {
    return anyProspect_ != null;
  }
  /**
   * <code>.google.protobuf.Any anyProspect = 4;</code>
   */
  public com.google.protobuf.Any getAnyProspect() {
    return anyProspect_ == null ? com.google.protobuf.Any.getDefaultInstance() : anyProspect_;
  }
  /**
   * <code>.google.protobuf.Any anyProspect = 4;</code>
   */
  public com.google.protobuf.AnyOrBuilder getAnyProspectOrBuilder() {
    return getAnyProspect();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (prospectId_ != 0L) {
      output.writeInt64(1, prospectId_);
    }
    if (prospectTypeCase_ == 2) {
      output.writeMessage(2, (com.lending.proto.Business) prospectType_);
    }
    if (prospectTypeCase_ == 3) {
      output.writeMessage(3, (com.lending.proto.Person) prospectType_);
    }
    if (anyProspect_ != null) {
      output.writeMessage(4, getAnyProspect());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (prospectId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, prospectId_);
    }
    if (prospectTypeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.lending.proto.Business) prospectType_);
    }
    if (prospectTypeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.lending.proto.Person) prospectType_);
    }
    if (anyProspect_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAnyProspect());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lending.proto.Prospect)) {
      return super.equals(obj);
    }
    com.lending.proto.Prospect other = (com.lending.proto.Prospect) obj;

    boolean result = true;
    result = result && (getProspectId()
        == other.getProspectId());
    result = result && (hasAnyProspect() == other.hasAnyProspect());
    if (hasAnyProspect()) {
      result = result && getAnyProspect()
          .equals(other.getAnyProspect());
    }
    result = result && getProspectTypeCase().equals(
        other.getProspectTypeCase());
    if (!result) return false;
    switch (prospectTypeCase_) {
      case 2:
        result = result && getBusiness()
            .equals(other.getBusiness());
        break;
      case 3:
        result = result && getPerson()
            .equals(other.getPerson());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROSPECTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProspectId());
    if (hasAnyProspect()) {
      hash = (37 * hash) + ANYPROSPECT_FIELD_NUMBER;
      hash = (53 * hash) + getAnyProspect().hashCode();
    }
    switch (prospectTypeCase_) {
      case 2:
        hash = (37 * hash) + BUSINESS_FIELD_NUMBER;
        hash = (53 * hash) + getBusiness().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPerson().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lending.proto.Prospect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Prospect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Prospect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Prospect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Prospect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Prospect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Prospect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lending.proto.Prospect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lending.proto.Prospect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lending.proto.Prospect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lending.proto.Prospect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lending.proto.Prospect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lending.proto.Prospect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lending.proto.Prospect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lending.proto.Prospect)
      com.lending.proto.ProspectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lending.proto.ProspectOuterClass.internal_static_com_lending_proto_Prospect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lending.proto.ProspectOuterClass.internal_static_com_lending_proto_Prospect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lending.proto.Prospect.class, com.lending.proto.Prospect.Builder.class);
    }

    // Construct using com.lending.proto.Prospect.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      prospectId_ = 0L;

      if (anyProspectBuilder_ == null) {
        anyProspect_ = null;
      } else {
        anyProspect_ = null;
        anyProspectBuilder_ = null;
      }
      prospectTypeCase_ = 0;
      prospectType_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lending.proto.ProspectOuterClass.internal_static_com_lending_proto_Prospect_descriptor;
    }

    public com.lending.proto.Prospect getDefaultInstanceForType() {
      return com.lending.proto.Prospect.getDefaultInstance();
    }

    public com.lending.proto.Prospect build() {
      com.lending.proto.Prospect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lending.proto.Prospect buildPartial() {
      com.lending.proto.Prospect result = new com.lending.proto.Prospect(this);
      result.prospectId_ = prospectId_;
      if (prospectTypeCase_ == 2) {
        if (businessBuilder_ == null) {
          result.prospectType_ = prospectType_;
        } else {
          result.prospectType_ = businessBuilder_.build();
        }
      }
      if (prospectTypeCase_ == 3) {
        if (personBuilder_ == null) {
          result.prospectType_ = prospectType_;
        } else {
          result.prospectType_ = personBuilder_.build();
        }
      }
      if (anyProspectBuilder_ == null) {
        result.anyProspect_ = anyProspect_;
      } else {
        result.anyProspect_ = anyProspectBuilder_.build();
      }
      result.prospectTypeCase_ = prospectTypeCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lending.proto.Prospect) {
        return mergeFrom((com.lending.proto.Prospect)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lending.proto.Prospect other) {
      if (other == com.lending.proto.Prospect.getDefaultInstance()) return this;
      if (other.getProspectId() != 0L) {
        setProspectId(other.getProspectId());
      }
      if (other.hasAnyProspect()) {
        mergeAnyProspect(other.getAnyProspect());
      }
      switch (other.getProspectTypeCase()) {
        case BUSINESS: {
          mergeBusiness(other.getBusiness());
          break;
        }
        case PERSON: {
          mergePerson(other.getPerson());
          break;
        }
        case PROSPECTTYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lending.proto.Prospect parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lending.proto.Prospect) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int prospectTypeCase_ = 0;
    private java.lang.Object prospectType_;
    public ProspectTypeCase
        getProspectTypeCase() {
      return ProspectTypeCase.forNumber(
          prospectTypeCase_);
    }

    public Builder clearProspectType() {
      prospectTypeCase_ = 0;
      prospectType_ = null;
      onChanged();
      return this;
    }


    private long prospectId_ ;
    /**
     * <code>int64 prospectId = 1;</code>
     */
    public long getProspectId() {
      return prospectId_;
    }
    /**
     * <code>int64 prospectId = 1;</code>
     */
    public Builder setProspectId(long value) {
      
      prospectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 prospectId = 1;</code>
     */
    public Builder clearProspectId() {
      
      prospectId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.lending.proto.Business, com.lending.proto.Business.Builder, com.lending.proto.BusinessOrBuilder> businessBuilder_;
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public boolean hasBusiness() {
      return prospectTypeCase_ == 2;
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public com.lending.proto.Business getBusiness() {
      if (businessBuilder_ == null) {
        if (prospectTypeCase_ == 2) {
          return (com.lending.proto.Business) prospectType_;
        }
        return com.lending.proto.Business.getDefaultInstance();
      } else {
        if (prospectTypeCase_ == 2) {
          return businessBuilder_.getMessage();
        }
        return com.lending.proto.Business.getDefaultInstance();
      }
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public Builder setBusiness(com.lending.proto.Business value) {
      if (businessBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prospectType_ = value;
        onChanged();
      } else {
        businessBuilder_.setMessage(value);
      }
      prospectTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public Builder setBusiness(
        com.lending.proto.Business.Builder builderForValue) {
      if (businessBuilder_ == null) {
        prospectType_ = builderForValue.build();
        onChanged();
      } else {
        businessBuilder_.setMessage(builderForValue.build());
      }
      prospectTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public Builder mergeBusiness(com.lending.proto.Business value) {
      if (businessBuilder_ == null) {
        if (prospectTypeCase_ == 2 &&
            prospectType_ != com.lending.proto.Business.getDefaultInstance()) {
          prospectType_ = com.lending.proto.Business.newBuilder((com.lending.proto.Business) prospectType_)
              .mergeFrom(value).buildPartial();
        } else {
          prospectType_ = value;
        }
        onChanged();
      } else {
        if (prospectTypeCase_ == 2) {
          businessBuilder_.mergeFrom(value);
        }
        businessBuilder_.setMessage(value);
      }
      prospectTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public Builder clearBusiness() {
      if (businessBuilder_ == null) {
        if (prospectTypeCase_ == 2) {
          prospectTypeCase_ = 0;
          prospectType_ = null;
          onChanged();
        }
      } else {
        if (prospectTypeCase_ == 2) {
          prospectTypeCase_ = 0;
          prospectType_ = null;
        }
        businessBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public com.lending.proto.Business.Builder getBusinessBuilder() {
      return getBusinessFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    public com.lending.proto.BusinessOrBuilder getBusinessOrBuilder() {
      if ((prospectTypeCase_ == 2) && (businessBuilder_ != null)) {
        return businessBuilder_.getMessageOrBuilder();
      } else {
        if (prospectTypeCase_ == 2) {
          return (com.lending.proto.Business) prospectType_;
        }
        return com.lending.proto.Business.getDefaultInstance();
      }
    }
    /**
     * <code>.com.lending.proto.Business business = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lending.proto.Business, com.lending.proto.Business.Builder, com.lending.proto.BusinessOrBuilder> 
        getBusinessFieldBuilder() {
      if (businessBuilder_ == null) {
        if (!(prospectTypeCase_ == 2)) {
          prospectType_ = com.lending.proto.Business.getDefaultInstance();
        }
        businessBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lending.proto.Business, com.lending.proto.Business.Builder, com.lending.proto.BusinessOrBuilder>(
                (com.lending.proto.Business) prospectType_,
                getParentForChildren(),
                isClean());
        prospectType_ = null;
      }
      prospectTypeCase_ = 2;
      onChanged();;
      return businessBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.lending.proto.Person, com.lending.proto.Person.Builder, com.lending.proto.PersonOrBuilder> personBuilder_;
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public boolean hasPerson() {
      return prospectTypeCase_ == 3;
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public com.lending.proto.Person getPerson() {
      if (personBuilder_ == null) {
        if (prospectTypeCase_ == 3) {
          return (com.lending.proto.Person) prospectType_;
        }
        return com.lending.proto.Person.getDefaultInstance();
      } else {
        if (prospectTypeCase_ == 3) {
          return personBuilder_.getMessage();
        }
        return com.lending.proto.Person.getDefaultInstance();
      }
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public Builder setPerson(com.lending.proto.Person value) {
      if (personBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prospectType_ = value;
        onChanged();
      } else {
        personBuilder_.setMessage(value);
      }
      prospectTypeCase_ = 3;
      return this;
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public Builder setPerson(
        com.lending.proto.Person.Builder builderForValue) {
      if (personBuilder_ == null) {
        prospectType_ = builderForValue.build();
        onChanged();
      } else {
        personBuilder_.setMessage(builderForValue.build());
      }
      prospectTypeCase_ = 3;
      return this;
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public Builder mergePerson(com.lending.proto.Person value) {
      if (personBuilder_ == null) {
        if (prospectTypeCase_ == 3 &&
            prospectType_ != com.lending.proto.Person.getDefaultInstance()) {
          prospectType_ = com.lending.proto.Person.newBuilder((com.lending.proto.Person) prospectType_)
              .mergeFrom(value).buildPartial();
        } else {
          prospectType_ = value;
        }
        onChanged();
      } else {
        if (prospectTypeCase_ == 3) {
          personBuilder_.mergeFrom(value);
        }
        personBuilder_.setMessage(value);
      }
      prospectTypeCase_ = 3;
      return this;
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public Builder clearPerson() {
      if (personBuilder_ == null) {
        if (prospectTypeCase_ == 3) {
          prospectTypeCase_ = 0;
          prospectType_ = null;
          onChanged();
        }
      } else {
        if (prospectTypeCase_ == 3) {
          prospectTypeCase_ = 0;
          prospectType_ = null;
        }
        personBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public com.lending.proto.Person.Builder getPersonBuilder() {
      return getPersonFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    public com.lending.proto.PersonOrBuilder getPersonOrBuilder() {
      if ((prospectTypeCase_ == 3) && (personBuilder_ != null)) {
        return personBuilder_.getMessageOrBuilder();
      } else {
        if (prospectTypeCase_ == 3) {
          return (com.lending.proto.Person) prospectType_;
        }
        return com.lending.proto.Person.getDefaultInstance();
      }
    }
    /**
     * <code>.com.lending.proto.Person person = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lending.proto.Person, com.lending.proto.Person.Builder, com.lending.proto.PersonOrBuilder> 
        getPersonFieldBuilder() {
      if (personBuilder_ == null) {
        if (!(prospectTypeCase_ == 3)) {
          prospectType_ = com.lending.proto.Person.getDefaultInstance();
        }
        personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lending.proto.Person, com.lending.proto.Person.Builder, com.lending.proto.PersonOrBuilder>(
                (com.lending.proto.Person) prospectType_,
                getParentForChildren(),
                isClean());
        prospectType_ = null;
      }
      prospectTypeCase_ = 3;
      onChanged();;
      return personBuilder_;
    }

    private com.google.protobuf.Any anyProspect_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> anyProspectBuilder_;
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public boolean hasAnyProspect() {
      return anyProspectBuilder_ != null || anyProspect_ != null;
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public com.google.protobuf.Any getAnyProspect() {
      if (anyProspectBuilder_ == null) {
        return anyProspect_ == null ? com.google.protobuf.Any.getDefaultInstance() : anyProspect_;
      } else {
        return anyProspectBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public Builder setAnyProspect(com.google.protobuf.Any value) {
      if (anyProspectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        anyProspect_ = value;
        onChanged();
      } else {
        anyProspectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public Builder setAnyProspect(
        com.google.protobuf.Any.Builder builderForValue) {
      if (anyProspectBuilder_ == null) {
        anyProspect_ = builderForValue.build();
        onChanged();
      } else {
        anyProspectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public Builder mergeAnyProspect(com.google.protobuf.Any value) {
      if (anyProspectBuilder_ == null) {
        if (anyProspect_ != null) {
          anyProspect_ =
            com.google.protobuf.Any.newBuilder(anyProspect_).mergeFrom(value).buildPartial();
        } else {
          anyProspect_ = value;
        }
        onChanged();
      } else {
        anyProspectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public Builder clearAnyProspect() {
      if (anyProspectBuilder_ == null) {
        anyProspect_ = null;
        onChanged();
      } else {
        anyProspect_ = null;
        anyProspectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public com.google.protobuf.Any.Builder getAnyProspectBuilder() {
      
      onChanged();
      return getAnyProspectFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAnyProspectOrBuilder() {
      if (anyProspectBuilder_ != null) {
        return anyProspectBuilder_.getMessageOrBuilder();
      } else {
        return anyProspect_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : anyProspect_;
      }
    }
    /**
     * <code>.google.protobuf.Any anyProspect = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getAnyProspectFieldBuilder() {
      if (anyProspectBuilder_ == null) {
        anyProspectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getAnyProspect(),
                getParentForChildren(),
                isClean());
        anyProspect_ = null;
      }
      return anyProspectBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lending.proto.Prospect)
  }

  // @@protoc_insertion_point(class_scope:com.lending.proto.Prospect)
  private static final com.lending.proto.Prospect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lending.proto.Prospect();
  }

  public static com.lending.proto.Prospect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Prospect>
      PARSER = new com.google.protobuf.AbstractParser<Prospect>() {
    public Prospect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Prospect(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Prospect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Prospect> getParserForType() {
    return PARSER;
  }

  public com.lending.proto.Prospect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

