// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/prospect.proto

package com.lending.proto;

public interface ProspectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lending.proto.Prospect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 prospectId = 1;</code>
   */
  long getProspectId();

  /**
   * <code>.com.lending.proto.Business business = 2;</code>
   */
  boolean hasBusiness();
  /**
   * <code>.com.lending.proto.Business business = 2;</code>
   */
  com.lending.proto.Business getBusiness();
  /**
   * <code>.com.lending.proto.Business business = 2;</code>
   */
  com.lending.proto.BusinessOrBuilder getBusinessOrBuilder();

  /**
   * <code>.com.lending.proto.Person person = 3;</code>
   */
  boolean hasPerson();
  /**
   * <code>.com.lending.proto.Person person = 3;</code>
   */
  com.lending.proto.Person getPerson();
  /**
   * <code>.com.lending.proto.Person person = 3;</code>
   */
  com.lending.proto.PersonOrBuilder getPersonOrBuilder();

  /**
   * <code>.google.protobuf.Any anyProspect = 4;</code>
   */
  boolean hasAnyProspect();
  /**
   * <code>.google.protobuf.Any anyProspect = 4;</code>
   */
  com.google.protobuf.Any getAnyProspect();
  /**
   * <code>.google.protobuf.Any anyProspect = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getAnyProspectOrBuilder();

  public com.lending.proto.Prospect.ProspectTypeCase getProspectTypeCase();
}
