// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/loan.proto

package com.lending.proto;

/**
 * Protobuf type {@code com.lending.proto.Loan}
 */
public  final class Loan extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lending.proto.Loan)
    LoanOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Loan.newBuilder() to construct.
  private Loan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Loan() {
    status_ = "";
    calledDue_ = false;
    dateClosed_ = "";
    dateOpened_ = "";
    loanNumber_ = "";
    daysPastDue_ = 0L;
    currentOwner_ = "";
    transferFrom_ = "";
    sourceAccountNumber_ = "";
    amountPastDueInCents_ = 0L;
    currentBalanceInCents_ = 0L;
    lastPaymentContingent_ = false;
    transferEffectiveDate_ = "";
    calledDueAmountInCents_ = 0L;
    outstandingBalanceInCents_ = 0L;
    inCollectionBeforeClosed_ = false;
    originalLoanAmountInCents_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Loan(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 16: {

            calledDue_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dateClosed_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            dateOpened_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            loanNumber_ = s;
            break;
          }
          case 48: {

            daysPastDue_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            currentOwner_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            transferFrom_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceAccountNumber_ = s;
            break;
          }
          case 80: {

            amountPastDueInCents_ = input.readInt64();
            break;
          }
          case 88: {

            currentBalanceInCents_ = input.readInt64();
            break;
          }
          case 96: {

            lastPaymentContingent_ = input.readBool();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            transferEffectiveDate_ = s;
            break;
          }
          case 112: {

            calledDueAmountInCents_ = input.readInt64();
            break;
          }
          case 120: {

            outstandingBalanceInCents_ = input.readInt64();
            break;
          }
          case 136: {

            inCollectionBeforeClosed_ = input.readBool();
            break;
          }
          case 144: {

            originalLoanAmountInCents_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lending.proto.Lending.internal_static_com_lending_proto_Loan_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lending.proto.Lending.internal_static_com_lending_proto_Loan_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lending.proto.Loan.class, com.lending.proto.Loan.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 1;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLEDDUE_FIELD_NUMBER = 2;
  private boolean calledDue_;
  /**
   * <code>bool calledDue = 2;</code>
   */
  public boolean getCalledDue() {
    return calledDue_;
  }

  public static final int DATECLOSED_FIELD_NUMBER = 3;
  private volatile java.lang.Object dateClosed_;
  /**
   * <code>string dateClosed = 3;</code>
   */
  public java.lang.String getDateClosed() {
    java.lang.Object ref = dateClosed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateClosed_ = s;
      return s;
    }
  }
  /**
   * <code>string dateClosed = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDateClosedBytes() {
    java.lang.Object ref = dateClosed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateClosed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOPENED_FIELD_NUMBER = 4;
  private volatile java.lang.Object dateOpened_;
  /**
   * <code>string dateOpened = 4;</code>
   */
  public java.lang.String getDateOpened() {
    java.lang.Object ref = dateOpened_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateOpened_ = s;
      return s;
    }
  }
  /**
   * <code>string dateOpened = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDateOpenedBytes() {
    java.lang.Object ref = dateOpened_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateOpened_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOANNUMBER_FIELD_NUMBER = 5;
  private volatile java.lang.Object loanNumber_;
  /**
   * <code>string loanNumber = 5;</code>
   */
  public java.lang.String getLoanNumber() {
    java.lang.Object ref = loanNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loanNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string loanNumber = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLoanNumberBytes() {
    java.lang.Object ref = loanNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loanNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DAYSPASTDUE_FIELD_NUMBER = 6;
  private long daysPastDue_;
  /**
   * <code>int64 daysPastDue = 6;</code>
   */
  public long getDaysPastDue() {
    return daysPastDue_;
  }

  public static final int CURRENTOWNER_FIELD_NUMBER = 7;
  private volatile java.lang.Object currentOwner_;
  /**
   * <code>string currentOwner = 7;</code>
   */
  public java.lang.String getCurrentOwner() {
    java.lang.Object ref = currentOwner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentOwner_ = s;
      return s;
    }
  }
  /**
   * <code>string currentOwner = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentOwnerBytes() {
    java.lang.Object ref = currentOwner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentOwner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSFERFROM_FIELD_NUMBER = 8;
  private volatile java.lang.Object transferFrom_;
  /**
   * <code>string transferFrom = 8;</code>
   */
  public java.lang.String getTransferFrom() {
    java.lang.Object ref = transferFrom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transferFrom_ = s;
      return s;
    }
  }
  /**
   * <code>string transferFrom = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTransferFromBytes() {
    java.lang.Object ref = transferFrom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transferFrom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEACCOUNTNUMBER_FIELD_NUMBER = 9;
  private volatile java.lang.Object sourceAccountNumber_;
  /**
   * <code>string sourceAccountNumber = 9;</code>
   */
  public java.lang.String getSourceAccountNumber() {
    java.lang.Object ref = sourceAccountNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceAccountNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceAccountNumber = 9;</code>
   */
  public com.google.protobuf.ByteString
      getSourceAccountNumberBytes() {
    java.lang.Object ref = sourceAccountNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceAccountNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNTPASTDUEINCENTS_FIELD_NUMBER = 10;
  private long amountPastDueInCents_;
  /**
   * <code>int64 amountPastDueInCents = 10;</code>
   */
  public long getAmountPastDueInCents() {
    return amountPastDueInCents_;
  }

  public static final int CURRENTBALANCEINCENTS_FIELD_NUMBER = 11;
  private long currentBalanceInCents_;
  /**
   * <code>int64 currentBalanceInCents = 11;</code>
   */
  public long getCurrentBalanceInCents() {
    return currentBalanceInCents_;
  }

  public static final int LASTPAYMENTCONTINGENT_FIELD_NUMBER = 12;
  private boolean lastPaymentContingent_;
  /**
   * <code>bool lastPaymentContingent = 12;</code>
   */
  public boolean getLastPaymentContingent() {
    return lastPaymentContingent_;
  }

  public static final int TRANSFEREFFECTIVEDATE_FIELD_NUMBER = 13;
  private volatile java.lang.Object transferEffectiveDate_;
  /**
   * <code>string transferEffectiveDate = 13;</code>
   */
  public java.lang.String getTransferEffectiveDate() {
    java.lang.Object ref = transferEffectiveDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transferEffectiveDate_ = s;
      return s;
    }
  }
  /**
   * <code>string transferEffectiveDate = 13;</code>
   */
  public com.google.protobuf.ByteString
      getTransferEffectiveDateBytes() {
    java.lang.Object ref = transferEffectiveDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transferEffectiveDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLEDDUEAMOUNTINCENTS_FIELD_NUMBER = 14;
  private long calledDueAmountInCents_;
  /**
   * <code>int64 calledDueAmountInCents = 14;</code>
   */
  public long getCalledDueAmountInCents() {
    return calledDueAmountInCents_;
  }

  public static final int OUTSTANDINGBALANCEINCENTS_FIELD_NUMBER = 15;
  private long outstandingBalanceInCents_;
  /**
   * <code>int64 outstandingBalanceInCents = 15;</code>
   */
  public long getOutstandingBalanceInCents() {
    return outstandingBalanceInCents_;
  }

  public static final int INCOLLECTIONBEFORECLOSED_FIELD_NUMBER = 17;
  private boolean inCollectionBeforeClosed_;
  /**
   * <code>bool inCollectionBeforeClosed = 17;</code>
   */
  public boolean getInCollectionBeforeClosed() {
    return inCollectionBeforeClosed_;
  }

  public static final int ORIGINALLOANAMOUNTINCENTS_FIELD_NUMBER = 18;
  private long originalLoanAmountInCents_;
  /**
   * <code>int64 originalLoanAmountInCents = 18;</code>
   */
  public long getOriginalLoanAmountInCents() {
    return originalLoanAmountInCents_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
    }
    if (calledDue_ != false) {
      output.writeBool(2, calledDue_);
    }
    if (!getDateClosedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateClosed_);
    }
    if (!getDateOpenedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dateOpened_);
    }
    if (!getLoanNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, loanNumber_);
    }
    if (daysPastDue_ != 0L) {
      output.writeInt64(6, daysPastDue_);
    }
    if (!getCurrentOwnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, currentOwner_);
    }
    if (!getTransferFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, transferFrom_);
    }
    if (!getSourceAccountNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sourceAccountNumber_);
    }
    if (amountPastDueInCents_ != 0L) {
      output.writeInt64(10, amountPastDueInCents_);
    }
    if (currentBalanceInCents_ != 0L) {
      output.writeInt64(11, currentBalanceInCents_);
    }
    if (lastPaymentContingent_ != false) {
      output.writeBool(12, lastPaymentContingent_);
    }
    if (!getTransferEffectiveDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, transferEffectiveDate_);
    }
    if (calledDueAmountInCents_ != 0L) {
      output.writeInt64(14, calledDueAmountInCents_);
    }
    if (outstandingBalanceInCents_ != 0L) {
      output.writeInt64(15, outstandingBalanceInCents_);
    }
    if (inCollectionBeforeClosed_ != false) {
      output.writeBool(17, inCollectionBeforeClosed_);
    }
    if (originalLoanAmountInCents_ != 0L) {
      output.writeInt64(18, originalLoanAmountInCents_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
    }
    if (calledDue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, calledDue_);
    }
    if (!getDateClosedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateClosed_);
    }
    if (!getDateOpenedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dateOpened_);
    }
    if (!getLoanNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, loanNumber_);
    }
    if (daysPastDue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, daysPastDue_);
    }
    if (!getCurrentOwnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, currentOwner_);
    }
    if (!getTransferFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, transferFrom_);
    }
    if (!getSourceAccountNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sourceAccountNumber_);
    }
    if (amountPastDueInCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, amountPastDueInCents_);
    }
    if (currentBalanceInCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, currentBalanceInCents_);
    }
    if (lastPaymentContingent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, lastPaymentContingent_);
    }
    if (!getTransferEffectiveDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, transferEffectiveDate_);
    }
    if (calledDueAmountInCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, calledDueAmountInCents_);
    }
    if (outstandingBalanceInCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, outstandingBalanceInCents_);
    }
    if (inCollectionBeforeClosed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, inCollectionBeforeClosed_);
    }
    if (originalLoanAmountInCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(18, originalLoanAmountInCents_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lending.proto.Loan)) {
      return super.equals(obj);
    }
    com.lending.proto.Loan other = (com.lending.proto.Loan) obj;

    boolean result = true;
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && (getCalledDue()
        == other.getCalledDue());
    result = result && getDateClosed()
        .equals(other.getDateClosed());
    result = result && getDateOpened()
        .equals(other.getDateOpened());
    result = result && getLoanNumber()
        .equals(other.getLoanNumber());
    result = result && (getDaysPastDue()
        == other.getDaysPastDue());
    result = result && getCurrentOwner()
        .equals(other.getCurrentOwner());
    result = result && getTransferFrom()
        .equals(other.getTransferFrom());
    result = result && getSourceAccountNumber()
        .equals(other.getSourceAccountNumber());
    result = result && (getAmountPastDueInCents()
        == other.getAmountPastDueInCents());
    result = result && (getCurrentBalanceInCents()
        == other.getCurrentBalanceInCents());
    result = result && (getLastPaymentContingent()
        == other.getLastPaymentContingent());
    result = result && getTransferEffectiveDate()
        .equals(other.getTransferEffectiveDate());
    result = result && (getCalledDueAmountInCents()
        == other.getCalledDueAmountInCents());
    result = result && (getOutstandingBalanceInCents()
        == other.getOutstandingBalanceInCents());
    result = result && (getInCollectionBeforeClosed()
        == other.getInCollectionBeforeClosed());
    result = result && (getOriginalLoanAmountInCents()
        == other.getOriginalLoanAmountInCents());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + CALLEDDUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCalledDue());
    hash = (37 * hash) + DATECLOSED_FIELD_NUMBER;
    hash = (53 * hash) + getDateClosed().hashCode();
    hash = (37 * hash) + DATEOPENED_FIELD_NUMBER;
    hash = (53 * hash) + getDateOpened().hashCode();
    hash = (37 * hash) + LOANNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLoanNumber().hashCode();
    hash = (37 * hash) + DAYSPASTDUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDaysPastDue());
    hash = (37 * hash) + CURRENTOWNER_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentOwner().hashCode();
    hash = (37 * hash) + TRANSFERFROM_FIELD_NUMBER;
    hash = (53 * hash) + getTransferFrom().hashCode();
    hash = (37 * hash) + SOURCEACCOUNTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSourceAccountNumber().hashCode();
    hash = (37 * hash) + AMOUNTPASTDUEINCENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmountPastDueInCents());
    hash = (37 * hash) + CURRENTBALANCEINCENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentBalanceInCents());
    hash = (37 * hash) + LASTPAYMENTCONTINGENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLastPaymentContingent());
    hash = (37 * hash) + TRANSFEREFFECTIVEDATE_FIELD_NUMBER;
    hash = (53 * hash) + getTransferEffectiveDate().hashCode();
    hash = (37 * hash) + CALLEDDUEAMOUNTINCENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCalledDueAmountInCents());
    hash = (37 * hash) + OUTSTANDINGBALANCEINCENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOutstandingBalanceInCents());
    hash = (37 * hash) + INCOLLECTIONBEFORECLOSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInCollectionBeforeClosed());
    hash = (37 * hash) + ORIGINALLOANAMOUNTINCENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOriginalLoanAmountInCents());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lending.proto.Loan parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Loan parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Loan parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Loan parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Loan parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lending.proto.Loan parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lending.proto.Loan parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lending.proto.Loan parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lending.proto.Loan parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lending.proto.Loan parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lending.proto.Loan parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lending.proto.Loan parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lending.proto.Loan prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lending.proto.Loan}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lending.proto.Loan)
      com.lending.proto.LoanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lending.proto.Lending.internal_static_com_lending_proto_Loan_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lending.proto.Lending.internal_static_com_lending_proto_Loan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lending.proto.Loan.class, com.lending.proto.Loan.Builder.class);
    }

    // Construct using com.lending.proto.Loan.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = "";

      calledDue_ = false;

      dateClosed_ = "";

      dateOpened_ = "";

      loanNumber_ = "";

      daysPastDue_ = 0L;

      currentOwner_ = "";

      transferFrom_ = "";

      sourceAccountNumber_ = "";

      amountPastDueInCents_ = 0L;

      currentBalanceInCents_ = 0L;

      lastPaymentContingent_ = false;

      transferEffectiveDate_ = "";

      calledDueAmountInCents_ = 0L;

      outstandingBalanceInCents_ = 0L;

      inCollectionBeforeClosed_ = false;

      originalLoanAmountInCents_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lending.proto.Lending.internal_static_com_lending_proto_Loan_descriptor;
    }

    public com.lending.proto.Loan getDefaultInstanceForType() {
      return com.lending.proto.Loan.getDefaultInstance();
    }

    public com.lending.proto.Loan build() {
      com.lending.proto.Loan result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lending.proto.Loan buildPartial() {
      com.lending.proto.Loan result = new com.lending.proto.Loan(this);
      result.status_ = status_;
      result.calledDue_ = calledDue_;
      result.dateClosed_ = dateClosed_;
      result.dateOpened_ = dateOpened_;
      result.loanNumber_ = loanNumber_;
      result.daysPastDue_ = daysPastDue_;
      result.currentOwner_ = currentOwner_;
      result.transferFrom_ = transferFrom_;
      result.sourceAccountNumber_ = sourceAccountNumber_;
      result.amountPastDueInCents_ = amountPastDueInCents_;
      result.currentBalanceInCents_ = currentBalanceInCents_;
      result.lastPaymentContingent_ = lastPaymentContingent_;
      result.transferEffectiveDate_ = transferEffectiveDate_;
      result.calledDueAmountInCents_ = calledDueAmountInCents_;
      result.outstandingBalanceInCents_ = outstandingBalanceInCents_;
      result.inCollectionBeforeClosed_ = inCollectionBeforeClosed_;
      result.originalLoanAmountInCents_ = originalLoanAmountInCents_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lending.proto.Loan) {
        return mergeFrom((com.lending.proto.Loan)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lending.proto.Loan other) {
      if (other == com.lending.proto.Loan.getDefaultInstance()) return this;
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getCalledDue() != false) {
        setCalledDue(other.getCalledDue());
      }
      if (!other.getDateClosed().isEmpty()) {
        dateClosed_ = other.dateClosed_;
        onChanged();
      }
      if (!other.getDateOpened().isEmpty()) {
        dateOpened_ = other.dateOpened_;
        onChanged();
      }
      if (!other.getLoanNumber().isEmpty()) {
        loanNumber_ = other.loanNumber_;
        onChanged();
      }
      if (other.getDaysPastDue() != 0L) {
        setDaysPastDue(other.getDaysPastDue());
      }
      if (!other.getCurrentOwner().isEmpty()) {
        currentOwner_ = other.currentOwner_;
        onChanged();
      }
      if (!other.getTransferFrom().isEmpty()) {
        transferFrom_ = other.transferFrom_;
        onChanged();
      }
      if (!other.getSourceAccountNumber().isEmpty()) {
        sourceAccountNumber_ = other.sourceAccountNumber_;
        onChanged();
      }
      if (other.getAmountPastDueInCents() != 0L) {
        setAmountPastDueInCents(other.getAmountPastDueInCents());
      }
      if (other.getCurrentBalanceInCents() != 0L) {
        setCurrentBalanceInCents(other.getCurrentBalanceInCents());
      }
      if (other.getLastPaymentContingent() != false) {
        setLastPaymentContingent(other.getLastPaymentContingent());
      }
      if (!other.getTransferEffectiveDate().isEmpty()) {
        transferEffectiveDate_ = other.transferEffectiveDate_;
        onChanged();
      }
      if (other.getCalledDueAmountInCents() != 0L) {
        setCalledDueAmountInCents(other.getCalledDueAmountInCents());
      }
      if (other.getOutstandingBalanceInCents() != 0L) {
        setOutstandingBalanceInCents(other.getOutstandingBalanceInCents());
      }
      if (other.getInCollectionBeforeClosed() != false) {
        setInCollectionBeforeClosed(other.getInCollectionBeforeClosed());
      }
      if (other.getOriginalLoanAmountInCents() != 0L) {
        setOriginalLoanAmountInCents(other.getOriginalLoanAmountInCents());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lending.proto.Loan parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lending.proto.Loan) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private boolean calledDue_ ;
    /**
     * <code>bool calledDue = 2;</code>
     */
    public boolean getCalledDue() {
      return calledDue_;
    }
    /**
     * <code>bool calledDue = 2;</code>
     */
    public Builder setCalledDue(boolean value) {
      
      calledDue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool calledDue = 2;</code>
     */
    public Builder clearCalledDue() {
      
      calledDue_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object dateClosed_ = "";
    /**
     * <code>string dateClosed = 3;</code>
     */
    public java.lang.String getDateClosed() {
      java.lang.Object ref = dateClosed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateClosed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateClosed = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateClosedBytes() {
      java.lang.Object ref = dateClosed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateClosed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateClosed = 3;</code>
     */
    public Builder setDateClosed(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateClosed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateClosed = 3;</code>
     */
    public Builder clearDateClosed() {
      
      dateClosed_ = getDefaultInstance().getDateClosed();
      onChanged();
      return this;
    }
    /**
     * <code>string dateClosed = 3;</code>
     */
    public Builder setDateClosedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateClosed_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateOpened_ = "";
    /**
     * <code>string dateOpened = 4;</code>
     */
    public java.lang.String getDateOpened() {
      java.lang.Object ref = dateOpened_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateOpened_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateOpened = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateOpenedBytes() {
      java.lang.Object ref = dateOpened_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOpened_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateOpened = 4;</code>
     */
    public Builder setDateOpened(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateOpened_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateOpened = 4;</code>
     */
    public Builder clearDateOpened() {
      
      dateOpened_ = getDefaultInstance().getDateOpened();
      onChanged();
      return this;
    }
    /**
     * <code>string dateOpened = 4;</code>
     */
    public Builder setDateOpenedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateOpened_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object loanNumber_ = "";
    /**
     * <code>string loanNumber = 5;</code>
     */
    public java.lang.String getLoanNumber() {
      java.lang.Object ref = loanNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loanNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string loanNumber = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLoanNumberBytes() {
      java.lang.Object ref = loanNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loanNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string loanNumber = 5;</code>
     */
    public Builder setLoanNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loanNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string loanNumber = 5;</code>
     */
    public Builder clearLoanNumber() {
      
      loanNumber_ = getDefaultInstance().getLoanNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string loanNumber = 5;</code>
     */
    public Builder setLoanNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loanNumber_ = value;
      onChanged();
      return this;
    }

    private long daysPastDue_ ;
    /**
     * <code>int64 daysPastDue = 6;</code>
     */
    public long getDaysPastDue() {
      return daysPastDue_;
    }
    /**
     * <code>int64 daysPastDue = 6;</code>
     */
    public Builder setDaysPastDue(long value) {
      
      daysPastDue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 daysPastDue = 6;</code>
     */
    public Builder clearDaysPastDue() {
      
      daysPastDue_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object currentOwner_ = "";
    /**
     * <code>string currentOwner = 7;</code>
     */
    public java.lang.String getCurrentOwner() {
      java.lang.Object ref = currentOwner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentOwner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currentOwner = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentOwnerBytes() {
      java.lang.Object ref = currentOwner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currentOwner = 7;</code>
     */
    public Builder setCurrentOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currentOwner = 7;</code>
     */
    public Builder clearCurrentOwner() {
      
      currentOwner_ = getDefaultInstance().getCurrentOwner();
      onChanged();
      return this;
    }
    /**
     * <code>string currentOwner = 7;</code>
     */
    public Builder setCurrentOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentOwner_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transferFrom_ = "";
    /**
     * <code>string transferFrom = 8;</code>
     */
    public java.lang.String getTransferFrom() {
      java.lang.Object ref = transferFrom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transferFrom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transferFrom = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTransferFromBytes() {
      java.lang.Object ref = transferFrom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transferFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transferFrom = 8;</code>
     */
    public Builder setTransferFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transferFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transferFrom = 8;</code>
     */
    public Builder clearTransferFrom() {
      
      transferFrom_ = getDefaultInstance().getTransferFrom();
      onChanged();
      return this;
    }
    /**
     * <code>string transferFrom = 8;</code>
     */
    public Builder setTransferFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transferFrom_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceAccountNumber_ = "";
    /**
     * <code>string sourceAccountNumber = 9;</code>
     */
    public java.lang.String getSourceAccountNumber() {
      java.lang.Object ref = sourceAccountNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceAccountNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceAccountNumber = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSourceAccountNumberBytes() {
      java.lang.Object ref = sourceAccountNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceAccountNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceAccountNumber = 9;</code>
     */
    public Builder setSourceAccountNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceAccountNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceAccountNumber = 9;</code>
     */
    public Builder clearSourceAccountNumber() {
      
      sourceAccountNumber_ = getDefaultInstance().getSourceAccountNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceAccountNumber = 9;</code>
     */
    public Builder setSourceAccountNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceAccountNumber_ = value;
      onChanged();
      return this;
    }

    private long amountPastDueInCents_ ;
    /**
     * <code>int64 amountPastDueInCents = 10;</code>
     */
    public long getAmountPastDueInCents() {
      return amountPastDueInCents_;
    }
    /**
     * <code>int64 amountPastDueInCents = 10;</code>
     */
    public Builder setAmountPastDueInCents(long value) {
      
      amountPastDueInCents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amountPastDueInCents = 10;</code>
     */
    public Builder clearAmountPastDueInCents() {
      
      amountPastDueInCents_ = 0L;
      onChanged();
      return this;
    }

    private long currentBalanceInCents_ ;
    /**
     * <code>int64 currentBalanceInCents = 11;</code>
     */
    public long getCurrentBalanceInCents() {
      return currentBalanceInCents_;
    }
    /**
     * <code>int64 currentBalanceInCents = 11;</code>
     */
    public Builder setCurrentBalanceInCents(long value) {
      
      currentBalanceInCents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currentBalanceInCents = 11;</code>
     */
    public Builder clearCurrentBalanceInCents() {
      
      currentBalanceInCents_ = 0L;
      onChanged();
      return this;
    }

    private boolean lastPaymentContingent_ ;
    /**
     * <code>bool lastPaymentContingent = 12;</code>
     */
    public boolean getLastPaymentContingent() {
      return lastPaymentContingent_;
    }
    /**
     * <code>bool lastPaymentContingent = 12;</code>
     */
    public Builder setLastPaymentContingent(boolean value) {
      
      lastPaymentContingent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool lastPaymentContingent = 12;</code>
     */
    public Builder clearLastPaymentContingent() {
      
      lastPaymentContingent_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object transferEffectiveDate_ = "";
    /**
     * <code>string transferEffectiveDate = 13;</code>
     */
    public java.lang.String getTransferEffectiveDate() {
      java.lang.Object ref = transferEffectiveDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transferEffectiveDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transferEffectiveDate = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTransferEffectiveDateBytes() {
      java.lang.Object ref = transferEffectiveDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transferEffectiveDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transferEffectiveDate = 13;</code>
     */
    public Builder setTransferEffectiveDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transferEffectiveDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transferEffectiveDate = 13;</code>
     */
    public Builder clearTransferEffectiveDate() {
      
      transferEffectiveDate_ = getDefaultInstance().getTransferEffectiveDate();
      onChanged();
      return this;
    }
    /**
     * <code>string transferEffectiveDate = 13;</code>
     */
    public Builder setTransferEffectiveDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transferEffectiveDate_ = value;
      onChanged();
      return this;
    }

    private long calledDueAmountInCents_ ;
    /**
     * <code>int64 calledDueAmountInCents = 14;</code>
     */
    public long getCalledDueAmountInCents() {
      return calledDueAmountInCents_;
    }
    /**
     * <code>int64 calledDueAmountInCents = 14;</code>
     */
    public Builder setCalledDueAmountInCents(long value) {
      
      calledDueAmountInCents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 calledDueAmountInCents = 14;</code>
     */
    public Builder clearCalledDueAmountInCents() {
      
      calledDueAmountInCents_ = 0L;
      onChanged();
      return this;
    }

    private long outstandingBalanceInCents_ ;
    /**
     * <code>int64 outstandingBalanceInCents = 15;</code>
     */
    public long getOutstandingBalanceInCents() {
      return outstandingBalanceInCents_;
    }
    /**
     * <code>int64 outstandingBalanceInCents = 15;</code>
     */
    public Builder setOutstandingBalanceInCents(long value) {
      
      outstandingBalanceInCents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 outstandingBalanceInCents = 15;</code>
     */
    public Builder clearOutstandingBalanceInCents() {
      
      outstandingBalanceInCents_ = 0L;
      onChanged();
      return this;
    }

    private boolean inCollectionBeforeClosed_ ;
    /**
     * <code>bool inCollectionBeforeClosed = 17;</code>
     */
    public boolean getInCollectionBeforeClosed() {
      return inCollectionBeforeClosed_;
    }
    /**
     * <code>bool inCollectionBeforeClosed = 17;</code>
     */
    public Builder setInCollectionBeforeClosed(boolean value) {
      
      inCollectionBeforeClosed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool inCollectionBeforeClosed = 17;</code>
     */
    public Builder clearInCollectionBeforeClosed() {
      
      inCollectionBeforeClosed_ = false;
      onChanged();
      return this;
    }

    private long originalLoanAmountInCents_ ;
    /**
     * <code>int64 originalLoanAmountInCents = 18;</code>
     */
    public long getOriginalLoanAmountInCents() {
      return originalLoanAmountInCents_;
    }
    /**
     * <code>int64 originalLoanAmountInCents = 18;</code>
     */
    public Builder setOriginalLoanAmountInCents(long value) {
      
      originalLoanAmountInCents_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 originalLoanAmountInCents = 18;</code>
     */
    public Builder clearOriginalLoanAmountInCents() {
      
      originalLoanAmountInCents_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lending.proto.Loan)
  }

  // @@protoc_insertion_point(class_scope:com.lending.proto.Loan)
  private static final com.lending.proto.Loan DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lending.proto.Loan();
  }

  public static com.lending.proto.Loan getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Loan>
      PARSER = new com.google.protobuf.AbstractParser<Loan>() {
    public Loan parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Loan(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Loan> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Loan> getParserForType() {
    return PARSER;
  }

  public com.lending.proto.Loan getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

