// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain-protos/loan.proto

package com.lending.proto;

public interface LoanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lending.proto.Loan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bool calledDue = 2;</code>
   */
  boolean getCalledDue();

  /**
   * <code>string dateClosed = 3;</code>
   */
  java.lang.String getDateClosed();
  /**
   * <code>string dateClosed = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateClosedBytes();

  /**
   * <code>string dateOpened = 4;</code>
   */
  java.lang.String getDateOpened();
  /**
   * <code>string dateOpened = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateOpenedBytes();

  /**
   * <code>string loanNumber = 5;</code>
   */
  java.lang.String getLoanNumber();
  /**
   * <code>string loanNumber = 5;</code>
   */
  com.google.protobuf.ByteString
      getLoanNumberBytes();

  /**
   * <code>int64 daysPastDue = 6;</code>
   */
  long getDaysPastDue();

  /**
   * <code>string currentOwner = 7;</code>
   */
  java.lang.String getCurrentOwner();
  /**
   * <code>string currentOwner = 7;</code>
   */
  com.google.protobuf.ByteString
      getCurrentOwnerBytes();

  /**
   * <code>string transferFrom = 8;</code>
   */
  java.lang.String getTransferFrom();
  /**
   * <code>string transferFrom = 8;</code>
   */
  com.google.protobuf.ByteString
      getTransferFromBytes();

  /**
   * <code>string sourceAccountNumber = 9;</code>
   */
  java.lang.String getSourceAccountNumber();
  /**
   * <code>string sourceAccountNumber = 9;</code>
   */
  com.google.protobuf.ByteString
      getSourceAccountNumberBytes();

  /**
   * <code>int64 amountPastDueInCents = 10;</code>
   */
  long getAmountPastDueInCents();

  /**
   * <code>int64 currentBalanceInCents = 11;</code>
   */
  long getCurrentBalanceInCents();

  /**
   * <code>bool lastPaymentContingent = 12;</code>
   */
  boolean getLastPaymentContingent();

  /**
   * <code>string transferEffectiveDate = 13;</code>
   */
  java.lang.String getTransferEffectiveDate();
  /**
   * <code>string transferEffectiveDate = 13;</code>
   */
  com.google.protobuf.ByteString
      getTransferEffectiveDateBytes();

  /**
   * <code>int64 calledDueAmountInCents = 14;</code>
   */
  long getCalledDueAmountInCents();

  /**
   * <code>int64 outstandingBalanceInCents = 15;</code>
   */
  long getOutstandingBalanceInCents();

  /**
   * <code>bool inCollectionBeforeClosed = 17;</code>
   */
  boolean getInCollectionBeforeClosed();

  /**
   * <code>int64 originalLoanAmountInCents = 18;</code>
   */
  long getOriginalLoanAmountInCents();
}
